### ISSUE TITLE
can we get paypal transaction id

### ISSUE THREAD

**Issue by uresh** [kloon/WooCommerce-REST-API-Client-Library#101]
i need to get paypal transaction id how to do that using API

**Comment by uresh** [comment]
$client->orders->get( 122, array( 'filter[meta]' => true, 'status' => 'completed' ) );
and
$client->orders->get( null, array( 'filter[meta]' => true, 'status' => 'completed' ) );
tryied like this its not giving data

**Comment by maxrice** [comment]
try `$client->orders->get( null, array( 'status' => 'completed', 'filter[meta]' => 'true' ) )` :)

**Comment by uresh** [comment]
hi still it not gives . is there any thing to active in web :(

**Comment by maxrice** [comment]
do you see a `order_meta` element?

**Comment by uresh** [comment]
nop only [meta] element

**Comment by uresh** [comment]
hi stil didnt working it can you help me
