### ISSUE TITLE
php notice using ssl_verify

### ISSUE THREAD

**Issue by PetterRuud** [kloon/WooCommerce-REST-API-Client-Library#103]
Notice: curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead

**Comment by maxrice** [comment]
@PetterRuud which version of PHP did you notice this in?

**Comment by aaronk6** [comment]
I see this with version `5.5.9-1ubuntu4.11`.

**Comment by watermark** [comment]
I see this as well and I'm also using 5.5.9.  5.5.9 is the default version that comes with Ubuntu 14.04.  Setting "ssl_verify" to 2 in the options to the client does't remove the notice because you're casting the argument to a bool in the request's constructor.
