### ISSUE TITLE
Adding Simple products global attribues

### ISSUE THREAD

**Issue by Freshclicks** [kloon/WooCommerce-REST-API-Client-Library#107]
When adding simple products I can add products and product specific attributes, but I can't add global attributes using the example below. Is this a limit of the client library?

> 'attributes' => array(
>                        array(
>                            'name' => 'Manufacturer',
>                            'options' =>
>                                array(
>                                    'Sony'
>                                ),
>                            'visible' => true,
>                            'variation' => false,
>                        )

**Comment by kloon** [comment]
This is unfortunately a issue on WooCommerce API side, this is merely a client library for the API so it is limited to what the API supports and can do.
