### ISSUE TITLE
404 issue on Rest api

### ISSUE THREAD

**Issue by tctnpf** [kloon/WooCommerce-REST-API-Client-Library#11]
Hi 

```
i have configured the woocommerce and wordpress on my local machine .
```

and also i have generated the consumer key and consumer secret for my woocommece application.i needs to access the wordpress application usind REST API

my request url is as follows

localhost/wordpress/index.php?wc-api-route=/wc-api/orders

if i used above url means i got the following erros.

{"errors":[{"code":"woocommerce_api_authentication_error","message":"Consumer Key is missing"}]}

also i have checked with

://localhost/wordpress/wc-api/v1/orders

if i used the above URL means am getting the 404 error.

how to get the woocommerce api endpoints for my local configuration.

**Comment by senthilkumar04** [comment]
hi @maxrice i am new to this woo commerce rest api and even i have configured the same thing i am also geting the same 404 error and could you please tell how to configure the authentication over HTTP using Oauth in the local machine

**Comment by maxrice** [comment]
@senthilkumar04 use this library and you don't need to configure anything :)

**Comment by mahadevan01** [comment]
Hi,
Me too got same error. I tried to get all products details.

I installed woocommerce and created API keys and enabled REST API
![image](https://cloud.githubusercontent.com/assets/13848125/9326069/b3b0340e-45b4-11e5-98e9-7c5a2948b518.png)

I wrote C#(3.5) code like below
Step1: created one class file.Got code from internet.
public class WoocommerceApiClient
    {
        private static byte[] HashHMAC(byte[] key, byte[] message)
        {
            var hash = new HMACSHA256(key);
            return hash.ComputeHash(message);
        }

```
    private string Hash(string input)
    {
        using (SHA1Managed sha1 = new SHA1Managed())
        {
            var hash = sha1.ComputeHash(Encoding.UTF8.GetBytes(input));
            var sb = new StringBuilder(hash.Length*2);

            foreach (byte b in hash)
            {
                // can be "x2" if you want lowercase
                sb.Append(b.ToString("X2"));
            }

            return sb.ToString();
        }
    }

    public const string API_ENDPOINT = "wc-api/v2/";
    public string ApiUrl { get; set; }
    public string ConsumerSecret { get; set; }
    public string ConsumerKey { get; set; }
    public bool IsSsl { get; set; }

    public WoocommerceApiClient(string consumerKey, string consumerSecret, string storeUrl, bool isSsl )
    {
        isSsl = false;
        if (string.IsNullOrEmpty(consumerKey) || string.IsNullOrEmpty(consumerSecret) ||
            string.IsNullOrEmpty(storeUrl))
        {
            throw new ArgumentException("ConsumerKey, consumerSecret and storeUrl are required");
        }
        this.ConsumerKey = consumerKey;
        this.ConsumerSecret = consumerSecret;
        this.ApiUrl = storeUrl.TrimEnd('/') + "/" + API_ENDPOINT;
        this.IsSsl = isSsl;
    }

    public string GetAllProducts()
    {
        return MakeApiCall("products", new Dictionary<string, string>() {{"filter[limit]", "2000"}},"get");
    }
    //public string GetProducts()
    //{
    //    return MakeApiCall("products");
    //}

    private string MakeApiCall(string endpoint, Dictionary<string, string> parameters , string method )
    {
        parameters = null;

        if (parameters == null)
        {
            parameters = new Dictionary<string, string>();
        }
        parameters["oauth_consumer_key"] = this.ConsumerKey;
        parameters["oauth_timestamp"] =
            DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1, 0, 0, 0)).TotalSeconds.ToString();
        parameters["oauth_timestamp"] = parameters["oauth_timestamp"].Substring(0,
            parameters["oauth_timestamp"].IndexOf("."));
        parameters["oauth_nonce"] = Hash(parameters["oauth_timestamp"]);
        parameters["oauth_signature_method"] = "HMAC-SHA256";
        parameters["oauth_signature"] = GenerateSignature(parameters, method, endpoint);
        WebClient wc = new WebClient();
        StringBuilder sb = new StringBuilder();
        foreach (var pair in parameters)
        {
            sb.AppendFormat("&{0}={1}", HttpUtility.UrlEncode(pair.Key), HttpUtility.UrlEncode(pair.Value));
        }
        //var url = this.ApiUrl + endpoint + "?" + sb.ToString().Substring(1).Replace("%5b", "%5B").Replace("%5d", "%5D");
        var url = this.ApiUrl + endpoint + "?" + sb.ToString().Substring(1).Replace("%5b", "%5B").Replace("%5d", "%5D");
        var result = wc.DownloadString(url);
        return result;
    }

    private string GenerateSignature(Dictionary<string, string> parameters, string method, string endpoint)
    {
        var baserequesturi = Regex.Replace(HttpUtility.UrlEncode(this.ApiUrl + endpoint), "(%[0-9a-f][0-9a-f])", c => c.Value.ToUpper());
        var normalized = NormalizeParameters(parameters);

        var signingstring = string.Format("{0}&{1}&{2}", method, baserequesturi,
            string.Join("%26", normalized.OrderBy(x => x.Key).ToList().ConvertAll(x => x.Key + "%3D" + x.Value).ToArray()));
        var signature = 
            Convert.ToBase64String(HashHMAC(Encoding.UTF8.GetBytes(this.ConsumerSecret),
                Encoding.UTF8.GetBytes(signingstring)));
        Console.WriteLine(signature);
        return signature;
    }

    private Dictionary<string, string> NormalizeParameters(Dictionary<string, string> parameters)
    {
        var result = new Dictionary<string, string>();
        foreach (var pair in parameters)
        {
            var key = HttpUtility.UrlEncode(HttpUtility.UrlDecode(pair.Key));
            key = Regex.Replace(key, "(%[0-9a-f][0-9a-f])", c => c.Value.ToUpper()).Replace("%", "%25");
            var value = HttpUtility.UrlEncode(HttpUtility.UrlDecode(pair.Value));
            value = Regex.Replace(value, "(%[0-9a-f][0-9a-f])", c => c.Value.ToUpper()).Replace("%", "%25");
            result.Add(key, value);
        }
        return result;
    }
}
```

Step 2: For watch the result for this code i have Created one windows application. in buttun clik, i wrote code like below

 private void button1_Click(object sender, EventArgs e)
        {
            WoocommerceApiClient obj = new WoocommerceApiClient(
               "ck_73551d74cf3f79f2918e4b47643a2a1ae1f12e82",
               "cs_06552e9ba0036c2cf77c0193037cf550b52c9849",
               "http://localhost:81/wp/",
               false);

```
        string sMsg = obj.GetAllProducts();
        MessageBox.Show(sMsg);
    }
```

in url,i got 
http://localhost:81/wp/wc-api/v2/products?oauth_consumer_key=ck_73551d74cf3f79f2918e4b47643a2a1ae1f12e82&oauth_timestamp=1439887770&oauth_nonce=0DD1C34F6615B784D75703C074074EAE06A3C35E&oauth_signature_method=HMAC-SHA256&oauth_signature=xEaMWLyT7gqowJ3XcOpNG4SQ6hu3yMdLlF8JP%2bLZ85c%3d

Inside MakeAPICall methord i got following error.The remote server returned an error: (404) Not Found\
![image](https://cloud.githubusercontent.com/assets/13848125/9326121/284232f4-45b5-11e5-9273-601badfed27d.png)

Coditions:
1. I used 81 port.
2. I saw wampserver trun too green. but alert says offline. is there any issue. if so means how to solve?
![image](https://cloud.githubusercontent.com/assets/13848125/9326245/06aaa54e-45b6-11e5-8dce-c1f352772a2d.png)

My Questions.
1. WHat i need to do. I tried all permalink settings. Still i got issue.
2. I did not found wc-api/v2 folders in wp. I saw only api/v2 folder. i tried with that endpoint too. that time also same error.
3. Please correct my code send me. Or instruct me for any settings.
Is there any specific API for to access woocommerce+wordpress db.?
4 . Is there any sample project source code for access woocommerce API??

**Comment by kapildesai** [comment]
@mahadevan01
Did you find any solution to update a product ?
