### ISSUE TITLE
Error: Invalid Signature - provided signature does not match 

### ISSUE THREAD

**Issue by uresh** [kloon/WooCommerce-REST-API-Client-Library#111]
Error: Invalid Signature - provided signature does not match [woocommerce_api_authentication_error] 401 stdClass Object ( [headers] => Array ( [0] => Accept: application/json [1] => Content-Type: application/json [2] => User-Agent: WooCommerce API Client-PHP/2.0.0 ) [method] => PUT [url] =>......
url of the web
is there any problem with woocom update or wordpress update

**Comment by uresh** [comment]
Error comming when i try  and this worked previously should be prb with wordpress
$client->orders->update_status( $order_id, 'completed' )

**Comment by maxrice** [comment]
this is usually a theme or plugin conflict, or occasionally a server issue if you're running nginx. disable all plugins and switch to the default theme and if if the error goes away, then it's one of them.

**Comment by KulwinderKohli** [comment]
No , i think it is API issue, Please help...
