### ISSUE TITLE
Invalid JSON returned 

### ISSUE THREAD

**Issue by alizainprasla** [kloon/WooCommerce-REST-API-Client-Library#120]
**Getting this error:**
Invalid JSON returned for https://example.com/wc-api/v2/customers?consumer_key=ck_16c66efc72ca35a7f0e0bfca8e04bb534821076f&consumer_secret=cs_ec231bb6ea18eaa07c63d1488a14bdfd5331bf02.
0
stdClass Object
(
    [headers] => Array
        (
            [0] => Accept: application/json
            [1] => Content-Type: application/json
            [2] => User-Agent: WooCommerce API Client-PHP/2.0.1
        )

```
[method] => GET
[url] => https://example.com/wc-api/v2/customers?consumer_key=ck_16c66efc72ca35a7f0e0bfca8e04bb534821076f&consumer_secret=cs_ec231bb6ea18eaa07c63d1488a14bdfd5331bf02
[params] => Array
    (
        [consumer_key] => ck_16c66efc72ca35a7f0e0bfca8e04bb534821076f
        [consumer_secret] => cs_ec231bb6ea18eaa07c63d1488a14bdfd5331bf02
    )
[data] => Array
    (
    )
[body] => 
[duration] => 0.15993
```

)
stdClass Object
(
    [body] => 
    [code] => 0
    [headers] => Array
        (
        )
)

**Return valid url on**

$options = array(
    'debug'           => true,
    'return_as_array' => false,
    'validate_url'    => true,
    'timeout'         => 30,
    'ssl_verify'      => true,
);

**showing:**
Invalid URL, no WC API found at https://cubixcube.com/html/dvm/wc-api/v2/ -- ensure your store URL is correct and pretty permalinks are enabled. 404

**Comment by nganhtuan63** [comment]
Are you using a php docker container? I have used dockers for my local development environment and I've figured out that my php container doesn't know the local address. It works with a true existed domain. Trying to make my php container recognize the host.

**Comment by pipegris** [comment]
Hi!
I am using the client to create products I pull from an external API, I'm also getting "Invalid JSON returned for..." in some of my requests, but the code is 201, the body is an empty string "", the product get correctly created, but the code throws that exception.

**Comment by pipegris** [comment]
Digging in my server error logs I could see that some filter or hook was generating an error, once corrected, it could create products (well, most of the time)

**Comment by alizainprasla** [comment]
Yes i found same on server logs. if any hook or filter generates error you will get "Invalid JSON returned for.."

for debugging i start create logs on my plugin hooks

ob_start();
echo json_encode($product);
$out = ob_get_contents();
ob_end_clean();

$fo = fopen("mylog.log","w+");
fwrite($fo,$out);
fclose($fo);

**Comment by azizchouhan** [comment]
Well, when you will change your permalink settings , Plain to Post name, this error will disappear.

so change your site's permalink setting, dont use default setting
