### ISSUE TITLE
Support servers that can't handle PUT/PATCH/DELETE

### ISSUE THREAD

**Issue by judgej** [kloon/WooCommerce-REST-API-Client-Library#134]
This one has wasted me a day of work trying to trace on a client's site. It seems that some PHP hosting can only accept GET and POST. If a PUT, for example, is sent, then it is converted to a GET and the GET parameters are stripped off.

Don't ask why - I have no idea - it just happens. The symptoms is that using the V2 API to update a product over SSL results in the error "missing consumer key" even though it is all clearly sent and visible in the HTTP logs.

Now [WC has a built-in workaround for this](https://github.com/woothemes/woocommerce/blob/f7ea1d4c6a1f3751b80e807ef89b2968cb25c6e0/includes/api/v2/class-wc-api-server.php#L133). Requests can be sent as GET or POST, and an additional parameter `_method` can be added to indicate what the required method really is. Most front-end REST form handlers do a similar thing, since browsers can only handle GET or POST as form submit methods, so a hidden `_method=PUT` form parameter can be used to invoke the update functionality when the form is submitted. Laravel does this out of the box.

So, can this library support this? An option so that the PUT/PATCH/DELETE method is requested, it can be converted into a GET or POST and an additional GET parameter added instead to indicate what API action is really needed? Does that make sense, and it is something that would be considered?

**Comment by maxrice** [comment]
Seems reasonable to me, feel free to work up a PR. IIRC this is usually a server setting in Apache that can be disabled if you need a workaround in the meantime.

**Comment by judgej** [comment]
Okay, thanks. I'll put forward anything that I develop. Also noticed that WP has a built-in REST API too, and that has the same `_method` workaround built in.

Any idea what this server setting is? I can't find anything on Google because "rest", "get", "put" are all such common words, search is just not getting the context. I have no idea what the source of the problem is - PHP, FastCGI, Apache...?

**Comment by judgej** [comment]
Hmm, on IIS there is a webdav module that gets in the way of PUT and DELETE. There may be something similar for Linux-based control panels and Apache, that need to be disabled.

**Comment by maxrice** [comment]
I saw the issue a few times with the iOS app and it seemed to be either vhost configs that only allowed GET/POST methods, or something like `mod_security` that was blocking it.

**Comment by judgej** [comment]
We think the issue was a mod_security rule. The web hoster spotted that and removed it. On my servers I never run mod_security, because it always causes more problems than it seems to solve (there may be better ways to set it up, but there are always too many other things to deal with).

In my case PUT was being blocked on the client's server completely, so access was just falling back to the server's default GET index.php. With the mod_security rule removed, this issue is fixed for us, so I am unlikely to need to work on a PR for it. If we find servers that we cannot work around in the future, then I may be back to revisit it. Hopefully the ticket details will help people with a similar problem in the future, and I would be happy to jump in on a group effort to support the `_method` workaround if there is a demand.

**Comment by maxrice** [comment]
> On my servers I never run mod_security, because it always causes more problems than it seems to solve

hear hear! totally agree.

> With the mod_security rule removed, this issue is fixed for us

Good to hear, seems that this is always a better solution than trying to support the `_method` workaround. I'm closing this for now, can re-open if there's more interest.

**Comment by judgej** [comment]
I may have spoken too soon - still broken - so may well be revisiting this sooner rather than later. Will see tomorrow. Keep this issue closed for now, as I know where to come back.

**Comment by judgej** [comment]
I have made a change to support a new option when creating a `WC_API_Client` instance. The option is `fix_method` and defaults to `false`.

If set to `true`, any non-GET and non-POST API call will be sent as a POST, with the original method added as a GET parameter `_method`.

I have tried this deleting and updating a product, and it works like a dream. My server that is refusing to accept PUT or DELETE throws up the "consumer key is missing" error (because some module on the server is rewriting all PUT calls to GET index.php). With `method_fix` set to `true`, deleting and updating (including updating the deleted) products simply works.

I'm testing it with SSL both on and off.

**Comment by judgej** [comment]
It works in the constructor of `WC_API_Client_HTTP_Request`. If the `fix_method` option is passed in set, then the method is changed to POST and the old method is injected as the `_method` parameter at that point. When the request it dispatched, is just sends a POST and has no knowledge that a PUT or DELETE have been switched for that POST.

**Comment by judgej** [comment]
I have noticed while developing here that the timeout seems to be locked to 20 seconds regardless of what timeout is passed in. I have not been able to trace the cause of that, but it's something to be noted. I was getting the timeout when my dev server got locked out by fail2ban.

Another tiny change is the point at which CURLOPT_SSL_VERIFYHOST is set. This parameter takes an integer and not a boolean. `false` is now mapped to 0 and `true` is now mapped to 2. The old value 1 is deprecated in PHP 5.4 and generates warnings if used (the old "true" was being interpreted "1" and that was giving me warnings, so I had to fix it).

**Comment by judgej** [comment]
PR submitted. It's a pretty simple change. Let me know what you think - whether parameter name is appropriate, whether coding style is okay etc.

**Comment by judgej** [comment]
Finally, usage is simple:

``` php
$wc_api = new WC_API_Client($store_url, $consumer_key, $consumer_secret, [
    'fix_method' => true,
]);

// etc.
```

**Comment by xewl** [comment]
Your PR is magnificently working on my end too!
(Was having problems with invalid json being returned in the responses)
Thanks judgej!!
