### ISSUE TITLE
Can only export 64 orders max.

### ISSUE THREAD

**Issue by erickarbe** [kloon/WooCommerce-REST-API-Client-Library#137]
Hello - not sure if this is a bug or a feature that exists for a reason, but I am using the API to export orders. When I have more than 64 orders, it caps out. The max numbers of orders I can export is 64. 

I am using the example code like so: $client->orders->get( null, array( 'status' => 'completed' ) )

Any reason this might be happening?

**Comment by johnyfarrar** [comment]
What happens when you do this -

$client->orders->get(null, array( 'filter[limit]' => -1 ));

?

**Comment by erickarbe** [comment]
Johny,

Magic. That worked. I didn't realize I could pass that parameter in. Thanks a ton.

**Comment by johnyfarrar** [comment]
It's a double edged sword though. As if you get too many then it slows up.
