### ISSUE TITLE
get the list of tax_class with their rules and rates

### ISSUE THREAD

**Issue by avaisonet** [kloon/WooCommerce-REST-API-Client-Library#144]
Hi, 

I wanna get the list of tax_class with their rules and rates with kloon/WooCommerce-REST-API-Client-Library.

Does someone know how ?

Best Regards

**Comment by avaisonet** [comment]
I've already read the doc of the woocommerce api to this address : http://woothemes.github.io/woocommerce-rest-api-docs/v2.html.

But my problem is that I'm using the kloon/WooCommerce-REST-API-Client-Library to access api via php, and that there no doc for this only examples.

There isn't any example to access to a list of the woocommerce tax_class via API Client Library.

Currently I'm think that there is no way with kloon/WooCommerce-REST-API-Client-Library to access to this.

I'm not sure if there is a way to override or create any class to permit that.

Can someone help ?

Best Regards

**Comment by kloon** [comment]
@avaisonet this is just a client library for the official API, so if the API cannot return taxes then this client library cannot get that.

As you are aware by going through the API docs at http://woothemes.github.io/woocommerce-rest-api-docs/v2.html there is no call to get tax classes in WooCommerce so the client library cannot get that info for you as well.

**Comment by avaisonet** [comment]
Tanks you @kloon I'm better understanding ! ^^

Best Regards
