### ISSUE TITLE
How can I get select array from Product ID

### ISSUE THREAD

**Issue by RazV3R** [kloon/WooCommerce-REST-API-Client-Library#145]
I understand this will show all array:

print_r( $client->products->get( $product_id ) );

but What If I just want to it to show 'title', 'sku', and 'description'. What command can I use for this situation. 

I did try print_r( $client->products->get( $product_id,'title' ) ) but still doesn't work

**Comment by kloon** [comment]
@RazV3R Because the data is in the array you can just reference it.

eg

```
$product = $client->products->get( $product_id );
echo 'Title: ' . $product['title'];
```
