### ISSUE TITLE
shipping / delivery rate

### ISSUE THREAD

**Issue by wider2** [kloon/WooCommerce-REST-API-Client-Library#147]
Good day
I have the question about shipping / delivery rate

Is it possible to get shipping rates from WooCommerce with help of your library?
I need to list it for the user before making order

**Comment by kloon** [comment]
Hi @wider2 

This is just a PHP client library for the official WooCommerce API, if the API cannot do it then this library cannot.

Unfortunately WooCommerce API does not have the ability to work out shipping/delivery rates http://woothemes.github.io/woocommerce-rest-api-docs/v2.html

**Comment by wider2** [comment]
Good day
we can show available methods

```
$shipping_methods = WC()->shipping->load_shipping_methods();
//echo "<br>count=" . count($shipping_methods);
$active_methods = array();  

foreach ( $shipping_methods as $id => $shipping_method ) {
    // Only get enabled shipping methods and push them into our array
    if ( isset( $shipping_method->enabled ) && 'yes' === $shipping_method->enabled ) {
        $method_title = $shipping_method->title;
    echo "<br>method_title=" . $method_title;
        // Append a tag to international delivery in case the name doesn't indicate it
        if ( 'international_delivery' === $id ) {
            $method_title .= ' (International)';
        }
        array_push( $active_methods, $method_title );
    }
}
```

**Comment by wider2** [comment]
right now I am testing the algoritm, but not success yet....

$packages = WC()->shipping->get_packages();
foreach ($packages as $i => $package) {
    $chosen_method = isset(WC()->session->chosen_shipping_methods[$i]) ? WC()->session->chosen_shipping_methods[$i] : '';
    $rate = $package['rates'][$chosen_method]->cost;
    echo "<br>i=" . $i . "; chosen_method=" . $chosen_method . "; rate=" . $rate;
}

**Comment by kloon** [comment]
That is on your site side and not something the API returns standard. Unfortunately this client library is not related to General WooCommerce issues, for that please contact WooThemes.
