### ISSUE TITLE
Get all products

### ISSUE THREAD

**Issue by parg-programador** [kloon/WooCommerce-REST-API-Client-Library#148]
I don't know because when I try get the list of all products return only four? When in true I have 553.

I using this code:

``` php
var_dump($client->products->get());
```

How can I get all products or a interval per creation date or between ids?

**Comment by wider2** [comment]
Good morning
I am not the author of "WooCommerce-REST-API-Client-Library",
 but you can use my algoritm to filter records by period of dates

$adim=array(); $bdim=array();
if ($search_date_begin !="" || $search_date_end !="") {
    if ($search_date_begin !="") {
        $arow +=1;
        $adim[$arow] = 'filter[created_at_min]';
        $bdim[$arow] = $ymd_begin;     //yyyy.mm.dd 
    }
    if ($search_date_end !="") {
        $arow +=1;
        $adim[$arow] = 'filter[created_at_max]';
        $bdim[$arow] = $ymd_end;  //yyyy.mm.dd 
    }
}
$sparam = array_combine($adim, $bdim);
    $products = $client->products->get(null, $sparam );

**Comment by parg-programador** [comment]
Good afternoon,
I test it the script, but have a problem in my site, when I solve this let's try again.
Thank you.

**Comment by parg-programador** [comment]
Good Afternoon, again

I solve the problem in my site, one hacker discorvery my password of the wordpress database and change all titles to a meta tag to redirect the users for http://managedforexaccount-pamm.blogspot.com.br/, if you look this code:

``` html
<meta http-equiv="refresh" content="0; url=http://managedforexaccount-pamm.blogspot.com/">
```

Basically the hacker using the standart theme of wordpress (twentyfifteen) to insert one code in 404.php

``` php
/* (Web Shell b374k r3c0d3d by x'1n73ct|default pass:" 1n73ction ") */ 
$auth_pass = "9726255eec083aa56dc0449a21b33190"; 
```

After this, he using user permission to read wp-config.php, to solve this I change de permission to 0600, before was 0644.

I've tried but now is not returning any product.

``` php
    if ($api_method == 'listar') {
        $arow = -1;
        $adim = array();
        $bdim = array();

        $search_date_begin = date("Y.m") . '.01';
        $search_date_end = date("Y.m.d");

        if ($search_date_begin != "" || $search_date_end != "") {
            if ($search_date_begin != "") {
                $arow +=1;
                $adim[$arow] = 'filter[created_at_min]';
                $bdim[$arow] = $search_date_begin; //yyyy.mm.dd
                //$bdim[$arow] = $ymd_begin; //yyyy.mm.dd
            }
            if ($search_date_end != "") {
                $arow +=1;
                $adim[$arow] = 'filter[created_at_max]';
                $bdim[$arow] = $search_date_end; //yyyy.mm.dd
                //$bdim[$arow] = $ymd_end; //yyyy.mm.dd
            }
        }
        $sparam = array_combine($adim, $bdim);
        $products = $client->products->get(null, $sparam);

        echo "Intervalo de $search_date_begin a $search_date_end<br/>";
        echo '<strong>Quantidade:</strong> ' . count($products) . '<br/><br/><pre>' . json_encode($products) . '</pre>';
    }
```

**Comment by parg-programador** [comment]
I managed using a filter of limit to show more products, can be possible to pagination, look this link http://woothemes.github.io/woocommerce-rest-api-docs/#pagination

``` php
    if ($api_method == 'listar') {
        //$arow = -1;
        $adim = array('filter[limit]');
        $bdim = array('15');

        $sparam = array_combine($adim, $bdim);
        $products = $client->products->get(null, $sparam);

        echo "Intervalo de $search_date_begin a $search_date_end<br/>";
        echo '<strong>Quantidade:</strong> ' . count($products->products) . '<br/><br/><pre>' . json_encode($products) . '</pre>';
    }
```

at the current moment, this works to me, but think so best if having documentation specifically for use of this library, we cloud using the wiki of github https://github.com/kloon/WooCommerce-REST-API-Client-Library/wiki

**Comment by wider2** [comment]
Agree
there are could be different approaches to filter returned records...
