### ISSUE TITLE
Missing creating a new order function.

### ISSUE THREAD

**Issue by sanojbogoda** [kloon/WooCommerce-REST-API-Client-Library#150]
I'm trying to create a native android app for woocommerce. Customers should be able to purchase via the app. 
How to place an order with the rest api?
I could not find a function to POST order parameters, I can find functions only to view data.
Is there a way to post an order, something like below?

$client -> createOrder ( $array_product );

Let me know please.

How to process Paypal from the API?

**Comment by kloon** [comment]
@sanojbogoda In the future please search or look through the code before creating an issue.

Order creation is supported, you can use this function https://github.com/kloon/WooCommerce-REST-API-Client-Library/blob/master/lib/woocommerce-api/resources/class-wc-api-client-resource-orders.php#L54-L62

**Comment by sanojbogoda** [comment]
Thank you kloon! 
Sorry for missing the code.

Basically I just need to find out about add to cart and check out functions.
May I check, is there a documentation for this?
