### ISSUE TITLE
get_categories() returns {"errors":[{"code":"200","message":"cURL HTTP error 200"}]}

### ISSUE THREAD

**Issue by Choxmi** [kloon/WooCommerce-REST-API-Client-Library#176]
I'm trying to get categories using `get_categories()` it is working fine in one Wordpress site. It returns categories in the correct way. `{"product_categories":[{"id":150,"name":"3D`Art","slug":"3d-art","parent":0,"description":"","display":"default","image":"","count":2}]}` 

But in another site I'm using the same method. But it returns `{"errors":[{"code":"200","message":"cURL HTTP error 200"}]}`  

I tried adding `$wc_api->get_orders( array( 'filter[limit]' => 10 ) );` it returns nothing. 

@zeeshan-m 's answer also not working for me. Please help me on this.

This is my code,
`<?php`

`error_reporting( E_ALL );`
`ini_set( 'display_errors', 'On' );`
`require_once "../client.php";`

`$consumer_key = '#################';`
`$consumer_secret = '################';`
`$store_url = 'http://xxxxxx/';`

`$wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );`

`echo json_encode( $wc_api->get_categories() );`
`

**Comment by zeeshan-m** [comment]
Hey,

Which version of the API are you using? Also, when you initialize your WC_API_Client you can pass in a fourth argument to enable request/response info:

```
$options = array( 'debug' => true);
$wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url, $options );
```

**Comment by Choxmi** [comment]
It worked with my previous version and after updating It returns an invalid json.

**Comment by Choxmi** [comment]
Hi,
@zeeshan-m I'm new for Woocommerce. I found the error. It passes the json with backslashes.
`"\ufeff{\"product_categories\":[{\"id\":140,\"name\":\"Accessories\",`
I don't know where this json come from. Please help me with this.
Thanks
