### ISSUE TITLE
Filter by Custom Taxonomies

### ISSUE THREAD

**Issue by inPhilly** [kloon/WooCommerce-REST-API-Client-Library#18]
It is unclear how to use the library to filter the results based on custom product taxonomy. Is this possible?

**Comment by Mte90** [comment]
what is the filter? the link point to an empty array :-/

**Comment by maxrice** [comment]
Sorry about that, the filter I think you'd need to use is [`woocommerce_api_query_args`](woocommerce_api_query_args) :smile_cat:

**Comment by borisdiakur** [comment]
Seems like the links are outdated once again : -/

**Comment by ravibarnwal** [comment]
This is the correct link https://github.com/woothemes/woocommerce/blob/f6526d72a72e3e2b110ed6c0f7b18329239c6667/includes/api/class-wc-api-resource.php#L217
