### ISSUE TITLE
i can't get all products

### ISSUE THREAD

**Issue by AntoninoPlatania** [kloon/WooCommerce-REST-API-Client-Library#205]
When i use that

print_r( $client->products->get() );

stamp 10 products only 

How i can get all my products?

Thanks

**Comment by jeanrinvil** [comment]
array( 'filter[limit]' => -1 ) in the get ()

**Comment by AntoninoPlatania** [comment]
thanks

**Comment by JavohirYakubov** [comment]
$client->products->get(array( 'filter[limit]' => -1 )) it's not working

error:
Error: Подходящий маршрут для URL и метода запроса не найден [woocommerce_api_no_route]
404

Please help me!
