### ISSUE TITLE
Update order status

### ISSUE THREAD

**Issue by eriqsenyonga** [kloon/WooCommerce-REST-API-Client-Library#215]
When trying to update order with 
$client->orders->update_status($order_id_to_update, $status);

it creates new order and updates status for both the original and the newly created order. Someone please help.

**Comment by eriqsenyonga** [comment]
Someone please help

**Comment by kloon** [comment]
It is possible that you might be running some code or a plugin that might be doing this when the update status endpoint is called. Perhaps also test with the official library and see if the same happens, if it does then its an issue on your site https://github.com/woocommerce/wc-api-php
