### ISSUE TITLE
Is there a way to send email ? (Invoice

### ISSUE THREAD

**Issue by MathieuDuboy** [kloon/WooCommerce-REST-API-Client-Library#217]
Hi, 
I'm working on this API and I want to send a customer invoice.
Is there a way to do that ?

With :
 $orders = $client->customers->get_orders($id) ;
I have all the information about the order and I want now to send an invoice email like I do in the admin part.

**Comment by kloon** [comment]
The WC API and this library does not cover sending of emails, you will have to write your own code to take care of that.
