### ISSUE TITLE
Update API to v1

### ISSUE THREAD

**Issue by MrSinor** [kloon/WooCommerce-REST-API-Client-Library#218]
I noticed that your php class uses WooCommerce Legacy v2 which is now deprecated.
Please update it to v1.
Here is Documentation: [http://woocommerce.github.io/woocommerce-rest-api-docs/](http://woocommerce.github.io/woocommerce-rest-api-docs/)

**Comment by kloon** [comment]
Hey, you can use the official library going forward for all the new endpoints https://github.com/woocommerce/wc-api-php
