### ISSUE TITLE
Convert Result to XML or JSON

### ISSUE THREAD

**Issue by IcuScc** [kloon/WooCommerce-REST-API-Client-Library#22]
Hello.
I'm triying the woocommerce api, but I'm not expert in php.
when execute you php example, i retrieve the result but i dont understand it. 

for example.
     print_r( $wc_api->get_products() );

is possible to covert the restult of the example.php in xml or json. have you an example?

thanks a lot

![products](https://cloud.githubusercontent.com/assets/5454095/3612013/00f7aaa2-0da4-11e4-86a6-0b32a484ab04.png)

**Comment by srkgroups** [comment]
Hello,

How can I convert the array / json output to XML format?

thanks & regards,
Manthan
