### ISSUE TITLE
Docs say that v3 is depreciated?

### ISSUE THREAD

**Issue by paligiannis** [kloon/WooCommerce-REST-API-Client-Library#220]
https://woocommerce.github.io/woocommerce-rest-api-docs/v3.html

There is a red line on that page insisting that v3 is depreciated. Is that correct? 
In the version tab they say 

> The v1 and v2 APIs will be removed in future versions.

Any ideas? Is v3 maintained cause when I change v2 to v3 my website cracks.

**Comment by kloon** [comment]
This library only supports v1 and v2, for all the newer endpoints I would suggest you rather use the official library https://github.com/woocommerce/wc-api-php

**Comment by paligiannis** [comment]
Will v3 will be integrated in your package? Is it mature? Is it in beta?
