### ISSUE TITLE
Get all products

### ISSUE THREAD

**Issue by charls637** [kloon/WooCommerce-REST-API-Client-Library#27]
Im having a problem to pull 426 products.

$wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );
print_r($wc_api->get_products());

it will only return 4 products which i don't know why?

i test my dev site also 27 products display only 10 of it.

Can you help me to provide any solution?

**Comment by wasimgit** [comment]
To retrieve all the products use the limit filter,

To get the 50 products ---- filter[limit]=50

To get all the products --- filter[limit]=-1

http://example.com/wc-api/v3/products?filter[limit]=50&oauth_consumer_key=ck_050f0a06050e2789b2c61d6bd66d2c97d3780580&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1448179257&oauth_nonce=Ac52xk&oauth_version=1.0&oauth_signature=eBm5/3CP6kw1K8F033wHnVpAKiw=

No need to change the code etc. only use the limit filter.

**Comment by imzeeshan** [comment]
There is a change in the latest version, the code is 
$client->products->get('',array( 'filter[limit]' => 100 )))
The first parameter to the get function is expected to be a product id, so leave it blank.

**Comment by borisdiakur** [comment]
Thanks @imzeeshan! Is this documented anywhere?

**Comment by vikasnetbeam** [comment]
Hi, i am having 25000+ products with 1500+ products.

how can i fetch these with 

$products = $client->products->get();

i am only getting 20 products

and after result i am getting notice:
Notice: Undefined property: stdClass::$title in /Applications/MAMP/htdocs/app/example/example.php on line 103

**Comment by nohyphen-dev** [comment]
@Wasimgit Yesss... you safe this issue, but Can I get URL of pagination here....

**Comment by wasimgit** [comment]
// Display 24 products per page.
add_filter( 'loop_shop_per_page', create_function( '$cols', 'return 24;' ), 20 );

**Comment by jezemery** [comment]
For the latest version of the WC API, use

`$products = $client->products->get(
                '',
                ['filter[limit]' => -1]
            );`

If nothing is returned, ensure the server hosting the WC API has enough memory to serve the requested products

**Comment by djeraseit** [comment]
Correct way is  'filter[posts_per_page]'=>-1

Latest version (using wc-api-php)

See theodis.com for details.

**Comment by mattiasghodsian** [comment]
Like @djeraseit told you

> 
'filter[posts_per_page]' => -1
>

**Comment by almustafago** [comment]
> For the latest version of the WC API, use
> 
> `$products = $client->products->get( '', ['filter[limit]' => -1] );`
> 
> If nothing is returned, ensure the server hosting the WC API has enough memory to serve the requested products

i filter to get all orders and put limit = -1  but it is not work  i give me just 83 orders and i have more than 3000 orders

**Comment by Sapython** [comment]
how can I get the list of all products using Python? I have 28 products and it only shows me only 9 products. You can use Woo-Commerce library for python but I am using requests and do it with a link like
https://sapython.co.in/wp-json/wc/v2/products?consumer_key=yourKey&consumer_secret=your_key
and it gives me a json response but with only 9 products.

**Comment by ponceleon** [comment]
is // =>  ?per_page=50

beatewn 1 to 100
