### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by pgiani** [kloon/WooCommerce-REST-API-Client-Library#30]
I'm trying to retrieve the PayPal Transaction ID form the order custom fields but it does not show up on the API wc_api->get_orders ().
Can it be done, if so How ?

**Comment by gongiskhan** [comment]
@maxrice Dude, as so many times before you saved my day! Whenever there's a difficult issue to solve on Wordpress playing with REST, be it WooCommerce API, User API, etc... you're always there providing the right answer. You are THE man! Thanks.

**Comment by maxrice** [comment]
@gongiskhan welcome, glad I could help :)

**Comment by amjad** [comment]
`http://www.example.com/wc-api/v3/orders?filter[meta]=true`

Using this.
