### ISSUE TITLE
2.2 WebHooks

### ISSUE THREAD

**Issue by peardox** [kloon/WooCommerce-REST-API-Client-Library#32]
I've made a few small hacks to the library as I wanted webhooks

Its a bit basic but works nicely

Line 17

	const API_ENDPOINT = 'wc-api/v2/';

Somewhere around line 277 do this

	public function get_webhooks() {
		return $this->_make_api_call( 'webhooks' );
	}

	public function set_webhook( $params = array() ) {
		return $this->_make_api_call( 'webhooks', array('webhook' => $params), 'POST' );
	}

	public function delete_webhook( $id ) {
		return $this->_make_api_call( 'webhooks/'.(int) $id, array(), 'DELETE' );
	}

It really needs some more work - I just delete en-mass a user's hooks and add them all again (don't wanna spend too much time on it if the API changes before release)

Usage is like this...

<?php
// Include the client library
error_reporting(65535);

require_once 'lib/class-wc-api-client.php';
 
$consumer_key = 'ck_12345678901234567890123456789012'; // Add your own Consumer Key here
$consumer_secret = 'cs_12345678901234567890123456789012'; // Add your own Consumer Secret here
$store_url = 'http://somestore.example.com'; // Add the home URL to the store you want to connect to here
$hookadd = 'https://someurl.example.com/wchook.php';

$index = ''; 
// Initialize the class
$wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );

$delhook = $wc_api->get_webhooks();
if(isset($delhook->webhooks)) {
	for($i=0; $i<count($delhook->webhooks); $i++) {
		$wc_api->delete_webhook($delhook->webhooks[$i]->id);
		}
	}

 $idx = $wc_api->set_webhook(array('topic' => 'customer.created', 'delivery_url' => $hookadd ));
 $idx = $wc_api->set_webhook(array('topic' => 'customer.updated', 'delivery_url' => $hookadd ));
 $idx = $wc_api->set_webhook(array('topic' => 'customer.deleted', 'delivery_url' => $hookadd ));
 $idx = $wc_api->set_webhook(array('topic' => 'order.created', 'delivery_url' => $hookadd ));
 $idx = $wc_api->set_webhook(array('topic' => 'order.updated', 'delivery_url' => $hookadd ));
 $idx = $wc_api->set_webhook(array('topic' => 'order.deleted', 'delivery_url' => $hookadd ));
 $idx = $wc_api->set_webhook(array('topic' => 'product.created', 'delivery_url' => $hookadd ));
 $idx = $wc_api->set_webhook(array('topic' => 'product.updated', 'delivery_url' => $hookadd ));
 $idx = $wc_api->set_webhook(array('topic' => 'product.deleted', 'delivery_url' => $hookadd ));

$index = $wc_api->get_webhooks();
echo "<pre>\n";
print_r( $index );
echo "</pre>\n";

This will then POST to wchook.php any customer actions (there's more you can do but that's all I really need for testing)

It's all nicely effective and is allowing me to migrate Shopify clients

**Comment by maxrice** [comment]
v2 is live, please give it a try :)
