### ISSUE TITLE
Something cool (auto keys)

### ISSUE THREAD

**Issue by peardox** [kloon/WooCommerce-REST-API-Client-Library#33]
This automatically keys a site on WPMU site creation when the user is signed up

Not required for solo sites - cut + paste those ones but for MU is's a boon

The endpoint gets all the data you need to capture the keys which can then be used with another sample I've supplied

Soz - not worked on WP for a few years now so trying to remember it all :)

I can tell you this works 100%

<?php
/**
 * @package Sitehooks
 * @version 0.1
 */
/*
Plugin Name: Sitehooks
Plugin URI: http://peardox.com/
Description: Sitehooks.
Author: Simon Booth
Version: 0.1
Author URI: http://peardox.com/
*/

// include_once('wp-content/plugins/woocommerce/includes/class-wc-install.php');

add_action( 'wpmu_new_blog', 'sitehooks_newsite', 10, 6 );
	
function sitehooks_newsite( $blog_id, $user_id, $domain, $path, $site_id, $meta ) {
	sitehooks_generate_api_key($user_id);
	$user = new WP_User( $user_id, '', $blog_id);
	
	$endpoint = "http://www.example.com/someplace.php";
	
	$body = json_encode(Array('blog_id' => $blog_id,
		'user_id' => $user_id,
		'domain' => $domain,
		'path' => $path,
		'site_id' => $site_id,
		'meta' => $meta,
		'login' => $user->data->user_login,
		'email' => $user->data->user_email,
		'nicename' => $user->data->user_nicename, 
		'woo_key' => $user->woocommerce_api_consumer_key,
		'woo_secret' => $user->woocommerce_api_consumer_secret,
		'display_name' => $user->data->display_name));
		
	wp_remote_post($endpoint, array('body' => $body));
	}

function sitehooks_generate_api_key( $user_id ) {
		if ( current_user_can( 'edit_user', $user_id ) ) {
			$user = get_userdata( $user_id );
			
			// consumer key
			if ( empty( $user->woocommerce_api_consumer_key ) ) {
				$consumer_key = 'ck_' . hash( 'md5', $user->user_login . date( 'U' ) . mt_rand() );
				update_user_meta( $user_id, 'woocommerce_api_consumer_key', $consumer_key );
				}

			// consumer secret
			if ( empty( $user->woocommerce_api_consumer_secret ) ) {
				$consumer_secret = 'cs_' . hash( 'md5', $user->ID . date( 'U' ) . mt_rand() );
				update_user_meta( $user_id, 'woocommerce_api_consumer_secret', $consumer_secret );
				}

			// permissions
			update_user_meta( $user_id, 'woocommerce_api_key_permissions', 'read_write' );
		}
	}

**Comment by maxrice** [comment]
I think https://github.com/woothemes/woocommerce/issues/6930 will cover this
