### ISSUE TITLE
Connecting to the mobile app through Rest API

### ISSUE THREAD

**Issue by krrishnajee** [kloon/WooCommerce-REST-API-Client-Library#37]
I'm developing a shopping cart Site and an App. I want to get product details from DB for my App, So I have recently used latest version of WooCommerce 2.1. And the main point is I don't have SSL in my domain. So my guess is I must use HTTP, And I don't have any idea about this. I found and read this document today. I'm confused at a point, How should I use this?

Where should I place this class-wc-api-client.php
- inside my theme root?

Where should I place this : 

<?php
    require_once 'class-wc-api-client.php';

```
$consumer_key = 'ck_fcedaba8f0fcb0fb4ae4f1211a75da72'; // Add your own Consumer Key here
$consumer_secret = 'cs_9914968ae9adafd3741c818bf6d704c7'; // Add your own Consumer Secret here
$store_url = 'http://localhost/'; // Add the home URL to the store you want to connect to here

// Initialize the class
$wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );
```

?>

What is $store_url?

How should I make requests?
http://mysite.com/wc-api/v2/products

I know that these are basics, This is my first App. So please help me guys.Thanks

**Comment by newmesiss** [comment]
Hello, I am developing a mobile app with cordova and AngularJS, is there any library like this for use with AngularJS?

**Comment by EvilDonkeyLondon** [comment]
Hi @newmesiss did you find an answer to your question? I am also building an app in AngularJS and I was also looking for a library like this.

**Comment by samnang-yin** [comment]
Hello, I am developing web-service for my mobile app with PHP and Wamp.
How can I use this rest-api.
I'm new with WooCommerce.
Please help me, guys.
Thanks.
