### ISSUE TITLE
WooCommerce Signatures

### ISSUE THREAD

**Issue by webdevguy** [kloon/WooCommerce-REST-API-Client-Library#4]
First of all, fantastic work on this API. It's simple and effective, and I appreciate all your hard work.

Secondly, I am currently experiencing an issue where WC is complaining that "Invalid Signature - provided signature does not match". The WC version i'm trying to access is 2.1.2 and i'm kind of at a loss as to what the problem might be. I've been trying to troubleshoot the generate_oauth_signature() function but to no avail so far.

Have you ever come across this, or do you have any suggestions on things I could check. Cheers =)

**Comment by Umakant-DM** [comment]
Hi,

I want to configure WooCommerce Rest API for my website, but when i trying to access products by this url (http://sws.thebluebell.in/wc-api/v2/products) then it will show error .

{"errors":[{"code":"woocommerce_api_authentication_error","message":"oauth_consumer_key parameter is missing"}]}

Please help me.

**Comment by shivamsahu13** [comment]
please use this library this will help you .

https://github.com/kloon/WooCommerce-REST-API-Client-Library

**Comment by jeffceriello** [comment]
Hi @Umakant-DM, I'm having the same issue that you're having. I am using WooCommerce REST API PHP Client Library and I manage to get the products appear on screen via PHP.

I need to get the products via the URL but when I go to http://example.com/wc-api/v3/products I get the same error you're getting.

Have you found a solution to this?

Thank you

**Comment by narayan48** [comment]
How can i access the woocommerce data through the rest api (through url). please let me know the steps
