### ISSUE TITLE
Customer Methods - Create Customer

### ISSUE THREAD

**Issue by alfiebesin** [kloon/WooCommerce-REST-API-Client-Library#40]
How to implement creating new customer using Woocommerce V2 REST API. Thanks.

**Comment by maxrice** [comment]
in v2:

```php
$customer = $client->customers->create( array( 'email' => 'test@test.com' ) );
```

you can see the full list of parameters here: http://woothemes.github.io/woocommerce-rest-api-docs/#customers-properties
