### ISSUE TITLE
Get all orders for product

### ISSUE THREAD

**Issue by zeeshan-m** [kloon/WooCommerce-REST-API-Client-Library#44]
Hey,

Quick question, is there a way to get all orders for a certain product given it's ID without pulling all orders and going through them one by one?

Thanks!

**Comment by SamsonovSlava** [comment]
SQL query to get all OrdersID for given ProductID:
SELECT order_id FROM `wp_woocommerce_order_items` WHERE order_item_id in (SELECT order_item_id FROM `wp_woocommerce_order_itemmeta` WHERE meta_key='_product_id' and meta_value=$Product_ID)

**Comment by jtsternberg** [comment]
This endpoint seems to only exist in the legacy files. Is this feature no longer supported?

**Comment by zeeshan-m** [comment]
When I logged this issue, it was pertaining to Legacy v1 of the API. That's now deprecated you can find the latest version here: http://woothemes.github.io/woocommerce-rest-api-docs/. You can get all orders using this end point: http://woothemes.github.io/woocommerce-rest-api-docs/#list-all-orders, but I'm not sure if that will allow you to filter by product id. I'm no longer using WooCommerce, so beyond that I can't help too much. Best of luck!
