### ISSUE TITLE
$wc_api->get_orders() not working correctly

### ISSUE THREAD

**Issue by zeeshan-m** [kloon/WooCommerce-REST-API-Client-Library#45]
Hey,

Using the following code:

```
$wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );
$orders = ( $wc_api->get_orders() );
```

I get back:

```
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => 200
                    [message] => cURL HTTP error 200
                )
        )
)
```

However, when I add 

```
$wc_api->set_return_as_object(false);
```

I get a JSON string back, however running json_decode returns a syntax error. I've tried to disabling/enabling WP_Debug, it still fails. I used to get a memory issue with this call (it returns over 650 orders back) but I've increased the memory limit to almost 10x what it used to be but it still won't work right. Any help is much appreciated.

**Comment by epsimatic** [comment]
@kloon I have found this topic by a chance. 

 `$wc_api->get_orders( array( 'filter[limit]' => 10 ) );` is extremely useful an looks totally undocumented anywhere else.

Thank you!
