### ISSUE TITLE
Update stock products

### ISSUE THREAD

**Issue by IcuScc** [kloon/WooCommerce-REST-API-Client-Library#48]
Hi,
Have anybody an example for update the stocks of products?

Thanks

**Comment by IcuScc** [comment]
ThankYou oBigZee. I go to try it.

**Comment by IcuScc** [comment]
I dont got it.
I want to make a php file for update the stock. for example
www.test.com/update_stock.php?idproduct=10&newstock=50&newstockstatus=instock

can you help me to do it?

Thank you

**Comment by oBigZee** [comment]
Hey,

So, what you'd need to do is:

    function update_product_stock($id, $quantity, $stockStatus) {
    	$productInfo = returnWC_API()->get_product($id)->{"product"};
    	$wc_product = new WC_Product($id);
    	$wc_product->set_stock($quantity);
        $wc_product->set_stock_status($stockStatus);
    	return true;
    }

stockStatus has to be either: 'outofstock' or 'instock'.

So, when you call the function above make sure you define a function called returnWC_API() which returns a WC_API_Client. So, my returnWC_API() function does the following:

    function returnWC_API() {
    	$consumer_key = 'yourConsumerKey';
    	$consumer_secret = 'yourConsumerPass';
    	$store_url = 'yourURL'; 
    	$wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );
      	return wc_api;
    }

and then for $id, $quantity, $stockStatus required for update_product_stock just set them to what you have in the url. Just make sure you clean it up first to make sure there's no malicious stuff going on.

**Comment by IcuScc** [comment]
Thanks oBigZee. i'll try it.

Another thing.
Today i get this error when i get all products. I have only 4 products.
            {"errors":[{"code":"0","message":"cURL HTTP error 0"}]}

i use:   $wc_api->get_products()
yesterday worked ok. 
do you know why??

**Comment by IcuScc** [comment]
Hi oBigZee, i dont got it.
in my wordpress web I create a new folder called WS. see the image

![01](https://cloud.githubusercontent.com/assets/5454095/5739218/d12b3816-9bf6-11e4-808c-c9f33c55fc7b.png)

Inside this new folder. i put 2 files
- test.php. you can see it in (https://www.dropbox.com/s/nk18h8e7r2mjkjc/test.php?dl=0)
- class-wc-api-client.php -> you can see it in (https://www.dropbox.com/s/zi7g73ngmztl23c/class-wc-api-client.php?dl=0)

when i call the test.php like www.biofor.es/ws/test.php
i retrieve this message
((( Notice: Use of undefined constant wc_api - assumed 'wc_api' in /var/www/vhost/biofor.es/home/html/ws/test.php on line 25 Fatal error: Call to a member function get_product() on a non-object in /var/www/vhost/biofor.es/home/html/ws/test.php on line 13 )))

¿Can you help me?

Thanks a lot...

**Comment by oBigZee** [comment]
I'm typing up an answer for you now, but please remove test.php. I think you left your consumer key and consumer password in there! Remove that. @IcuScc

**Comment by oBigZee** [comment]
@IcuScc 

Okay, so what you need to do is:

1. Remove the definition of WC_Product from test.php
2. Move returnWC_API() to right under 
```php
      require_once "class-wc-api-client.php";
```
3. Move update_product_stock to right under returnWC_API
4. Move 
```php
    update_product_stock(10,120,'instock');
    print_r("Fin");
```
to under update_product_stock

So, your final test.php should look like:
```php
error_reporting( E_ALL );
ini_set( 'display_errors', 'On' );
require_once "class-wc-api-client.php";
function returnWC_API() {
    $consumer_key = 'Key'; // Add your own Consumer Key here
    $consumer_secret = 'Password'; // Add your own Consumer Secret here
    $store_url = 'URL/'; // Add the home URL to the store you want to connect to here
    $wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );
    return wc_api;
}
function update_product_stock($id, $quantity, $stockStatus) {
    $productInfo = returnWC_API()->get_product($id)->{"product"};
    $wc_product = new WC_Product($id);
    $wc_product->set_stock($quantity);
    $wc_product->set_stock_status($stockStatus);
    return true;
}
update_product_stock(10,120,'instock');
print_r("Fin");
```

Your main issue is the fact that you're calling functions before they're declared. In your original code, you call update_product_stock on line 7, however it's defined on line 12. Also, within update_product_stock you call returnWC_API() which is defined on line 20. You have to make sure that whenever you call any function, or variable, or class, it's defined before you're using it. Reorganizing the code as mentioned above will do that.

**Comment by IcuScc** [comment]
thanks a lot @oBigZee.   I'm not php developer.
Now. i retrieve this message

(( Notice: Use of undefined constant wc_api - assumed 'wc_api' in /var/www/vhost/biofor.es/home/html/ws/test2.php on line 11 Fatal error: Call to a member function get_product() on a non-object in /var/www/vhost/biofor.es/home/html/ws/test2.php on line 14 ))

i create test2.php like this.
<?php
error_reporting( E_ALL );
ini_set( 'display_errors', 'On' );
require_once "class-wc-api-client.php";
function returnWC_API() {
	$consumer_key = 'my ck'; // Add your own Consumer Key here
	$consumer_secret = 'my cs'; // Add your own Consumer Secret here
	$store_url = 'http://www.biofor.es/'; // Add the home URL to the store you want to connect to here	
    $wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );
    return wc_api;
}
function update_product_stock($id, $quantity, $stockStatus) {
    $productInfo = returnWC_API()->get_product($id)->{"product"};
    $wc_product = new WC_Product($id);
    $wc_product->set_stock($quantity);
    $wc_product->set_stock_status($stockStatus);
    return true;
}
update_product_stock(2571,120,'instock');
print_r("Fin");
?>

whats wrong??
why give me this message??

**Comment by oBigZee** [comment]
In the return statement for returnWC_API, there's a typo
```php
return wc_api;
```
should be
```php
return $wc_api;
```

**Comment by IcuScc** [comment]
Correct @oBigZee  i added $ before wc_api.

I'm sorry, but now i retrieve this message

(( Fatal error: Class 'WC_Product' not found in /var/www/vhost/biofor.es/home/html/ws/test2.php on line 14 ))

what's wrong?
Where must be the WG_Product class?
thankyou

**Comment by oBigZee** [comment]
Hey,
I think you aren't loading wordpress. 
Add:
```php
require_once( '../wp-load.php' );
```
But, the path might be different for you. wp-load.php will be in the folder in which you installed wordpress. You need to put a path to that, for me it was '../wp-load.php'. This will load the wordpress/woocommerce dependencies, and it'll work from there.

**Comment by IcuScc** [comment]
@oBigZee Perfect!!... i can update the stock and status..
thankyou so much!!

i want to put my last test.php file for if somebody need it

---------------------------------------------------------------------
<?php
error_reporting( E_ALL );
ini_set( 'display_errors', 'On' );
require_once( '../wp-load.php' );
require_once "class-wc-api-client.php";

function returnWC_API() {
	$consumer_key = 'my_ck'; // Add your own Consumer Key here
	$consumer_secret = 'my_cs'; // Add your own Consumer Secret here
	$store_url = 'myurl/'; // Add the home URL to the store you want to connect to here	
    $wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );
    return $wc_api;
}
function update_product_stock($id, $quantity, $stockStatus) {
    $productInfo = returnWC_API()->get_product($id)->{"product"};
    $wc_product = new WC_Product($id);
    $wc_product->set_stock($quantity);
    $wc_product->set_stock_status($stockStatus);
    return true;
}
update_product_stock(2572,150,'instock');
print_r("Fin");
?>

**Comment by IcuScc** [comment]
Hi @oBigZee  again. I go to try to make the create and update products. I only want to write, sku, description, short description, prizes and variations. I hope to get it, but if you have any idea....
Thanks

**Comment by IcuScc** [comment]
Hi again. I put this function in WC_API_Client class
-------------------------------------------------------------------------------------------------------------------------------
 public function crear_producto( $data = array() ) 
 {
	$jsonInfArt=json_encode($data);
	return $this->_make_api_call( 'products/' .  $jsonInfArt, 'POST' );
 }

  
after in my php file i have this code
--------------------------------------------------------------------------------------------------------------------------------
<?php
error_reporting( E_ALL );
ini_set( 'display_errors', 'On' );
require_once( '../../wp-load.php' );
require_once "../class-wc-api-client_v2.php";

$aInfArt=array('product'	=>array(
			'title'				=> 'icu',
			'type'              => 'simple',
			'sku'               => 'icusky',
			'regular_price'		=> '100',
			'description'		=> 'Descripcion Larga',
			'short_description'	=> 'Descripcion Corta',
			'categories'	=>array('General'),
		));

if(isset( $_GET[ 'infart' ] ))
{
	$aInfArt = $_GET['infart'];
}

function returnWC_API()
{
	$consumer_key = 'ck_My'; 
	$consumer_secret = 'cs_My'; 
	$store_url = 'http://www.my.es/'; 

    $wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );
    return $wc_api;
}

function crea_producto($aInfoProducto)
{
	$productInfo = returnWC_API()->crear_producto($aInfoProducto)->{"product"};
	return $productInfo;
}

$aResultado=crea_producto($aInfArt) ;
print_r(json_encode($aResultado)) ;

?>

I get null result
whats wrong?? can you help me??

Thanks a lot

**Comment by oBigZee** [comment]
Hey,

Haven't really done much with creating products. But, if you're using the v2 api, refer to this: http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-product It'll walk you through the process.

**Comment by IcuScc** [comment]
thanks @oBigZee 
i see it, but i dont get it.
i need to create products without ssl..  i hope so to get it.

**Comment by maxrice** [comment]
in v2:

```php
$client->products->update_stock( $product_id, $quantity );
```

**Comment by IcuScc** [comment]
Hi max. 
excuse me for question again.

what sentence is necesary for update the stock of variation

Thanks

**Comment by maxrice** [comment]
same as above, but use the variation ID instead of the parent product ID.

**Comment by IcuScc** [comment]
thanks Max
I tryed this, yesterday, and don't works for me. I dont know why, because $client->products->get( $product_id_variation)  works okey.

my solution was to do update product with stock information.

i will to try again $client->products->update_stock( $product_id_variation, $quantity );

Thanks a lot.

**Comment by IcuScc** [comment]
Hi again and good mornig.
I have a question.

I've a product with several variations. Now i wont to disable one of them. I dont found what to do this. Is possible? how?

Thanks Max

**Comment by IcuScc** [comment]
Hi again,
I found the propertie. the propertie is visible=true or visible=false

My confusion was that property could not be used, because in the documentation put that is readonly.

Thanks.

**Comment by nitin2907** [comment]
Hi all,
I am using woocommerce plugin in wordpress & and place it inside /home/builhsqv/public_html/test/wp-contents/plugins/   location  And I have created a core php file inside /home/builhsqv/public_html/test/test.php, in this file i have written code to delete a individual Order line item. below is my code :-

//TEST.PHP
<?php
error_reporting(E_ALL );
require_once( dirname(**FILE**)."/wp-content/plugins/woocommerce/includes/wc-order-functions.php");
echo "Woocommerce";
$itemID = 1234;
echo $result = wc_delete_order_item($itemID);
print_r($result); 
?>

//wc-order-functions.php (File of woocommerce )
<?php
function wc_delete_order_item( $item_id ) {
global $wpdb;
$item_id = absint( $item_id );
if ( ! $item_id )
return false;
do_action( 'woocommerce_before_delete_order_item', $item_id );
$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->prefix}woocommerce_order_items WHERE order_item_id = %d", $item_id ) );
$wpdb->query( $wpdb->prepare( "DELETE FROM {$wpdb->prefix}woocommerce_order_itemmeta WHERE order_item_id = %d", $item_id ) );
do_action( 'woocommerce_delete_order_item', $item_id );
return true;
}
?>

when i run this file in browser, it's showing blank page.
but when i comment the require path and the calling function that i can see the echo message.

I want to deleted a order line item using php script in woocommerce.

any help would be appreciate.
thank you in advance.

Thanks & Regards,
Nitin Shukla
