### ISSUE TITLE
Get Products by SKU

### ISSUE THREAD

**Issue by IcuScc** [kloon/WooCommerce-REST-API-Client-Library#49]
Hi, i want to retrieve product by sku.
I'm using this sentence

     print_r( json_encode($wc_api->get_products(array( 'filter[sku]' => 'P' ))));

don't works. why?

else
     print_r( json_encode($wc_api->get_products(array( 'filter[created_at_min]' => '2014-10-01' ))));
works ok.

Thankyou

**Comment by maxrice** [comment]
in v2:

`$client->products->get_by_sku( $sku );`

**Comment by IcuScc** [comment]
Hi. Today I tryng V3 version... get product by sku fails..
