### ISSUE TITLE
Issue with oauth_timestamp

### ISSUE THREAD

**Issue by markessence** [kloon/WooCommerce-REST-API-Client-Library#50]
Hi,

Everything worked just fine until today when I have woocommerce_api_authentication_error [message] => oauth_timestamp Parameter missing. I did nothing to the source code. Double-checked and the line "$params['oauth_timestamp'] = time();" is there. 

I tried to manually set $paramString in the following code. curl_setopt( $ch, CURLOPT_URL, $this->_api_url . $endpoint . $paramString );

I do not have any oauth_timestamp error but obviously the signature is not good due to the fact that I had "&oauth_signature=".$this->generate_oauth_signature( $params, $method, $endpoint ) and there was no $params set up (did it manually).

So with original client library code I get oauth_timestamp missing and with it modified to include the timestamp manually in the request I get signature error

Please help

**Comment by maxrice** [comment]
please try with the v2 API and set `verbose_mode` to `true`

**Comment by itobe-de** [comment]
hey,

i just downloaded your sources and am receiving the same error message, regardless which API endpoints im tryin to access, it always says (except for the index):

Error: Parameter oauth_timestamp fehlt [woocommerce_api_authentication_error] 404 stdClass Object ( [headers] => Array ( [0] => Accept: application/json [1] => Content-Type: application/json [2] => User-Agent: WooCommerce API Client-PHP/2.0.0 ) [method] => GET [url] => http://mydomain.de/wc-api/v2/orders?oauth_consumer_key=key&oauth_timestamp=1433162723&oauth_nonce=nonce&oauth_signature_method=HMAC-SHA256&oauth_signature=sig [params] => Array ( [oauth_consumer_key] => key [oauth_timestamp] => 1433162723 [oauth_nonce] => nonce [oauth_signature_method] => HMAC-SHA256 [oauth_signature] => sig ) [data] => Array ( ) [body] => [duration] => 1.58404 ) stdClass Object ( [body] => {"errors":[{"code":"woocommerce_api_authentication_error","message":"Parameter oauth_timestamp fehlt"}]} [code] => 404 [headers] => Array ( [Date] => Mon, 01 Jun 2015 12:45:25 GMT [Content-Type] => application/json; charset=UTF-8 [Content-Length] => 104 [Connection] => keep-alive [Server] => Apache [Set-Cookie] => PHPSESSID=session; path=/ [Expires] => Thu, 19 Nov 1981 08:52:00 GMT [Cache-Control] => no-store, no-cache, must-revalidate, post-check=0, pre-check=0 [Pragma] => no-cache [Vary] => Accept-Encoding,User-Agent ) )

as you can see, it totally doesnt make any sense cuz theres obviously the oauth_timestamp parameter included in the request.

**Comment by maxrice** [comment]
This is probably your server removing the `oauth_timestamp` parameter, disable any security plugins and check mod_security logs

**Comment by itobe-de** [comment]
thanks a lot for the hint ill try that :)

**Comment by anabelle** [comment]
Did you manage to solve the issue? 

I'm having the same issue.

**Comment by itobe-de** [comment]
yes but not really, in fact it just didnt work with hosting WP/WC API
server on "machine A" and trying to access the API via the client library
on the same machine A

since i only wanted to test if some special value is returned by the API, i
moved on trying to access the API server on machine A via the client
library hosted on different machine B

sorry but we couldnt solve the issue on/with hosteurope servers, i dont
even know if its not possible to run API server and client on same machine
in general, but it worked on our local dev environment, but not on
production servers with different conf etc...

good luck :)

2015-07-07 23:50 GMT+02:00 Anabelle Handdoek <notifications@github.com>:
