### ISSUE TITLE
Invalid Signature - provided signature does not match

### ISSUE THREAD

**Issue by jaooe** [kloon/WooCommerce-REST-API-Client-Library#52]
I keep getting this,

	stdClass Object
	(
	    [errors] => Array
	        (
	            [0] => stdClass Object
	                (
	                    [code] => woocommerce_api_authentication_error
	                    [message] => Invalid Signature - provided signature does not match
	                )
	        )
	)

when calling;
```
    print_r($wc_api->make_custom_endpoint_call("products/",array(),'POST'));
```
When I call 
```
    print_r($wc_api->make_custom_endpoint_call("products",array(),'GET'));
```
I get no problems though...

**Comment by NickIvanter** [comment]
I had this problem too and [this change](https://github.com/kloon/WooCommerce-REST-API-Client-Library/pull/73) fixed it for me.

**Comment by maxrice** [comment]
thanks all, this should be fixed in v2
