### ISSUE TITLE
How to search for keywords?

### ISSUE THREAD

**Issue by alifax89** [kloon/WooCommerce-REST-API-Client-Library#53]
Hello, I have just a question... Is it possible to search for keywords using this wrapper? if yes, can you help me, because I didn't understand how can I do this!

**Comment by oBigZee** [comment]
Could you explain a little more what you're looking for? Do you want to search for products, users, or what?

**Comment by maxrice** [comment]
Use the `q` parameter:

```php
$client->orders->get( null, array( 'q' => 'your keyword' ) );
```
