### ISSUE TITLE
Help a newbie: POST orders from WooCommerce to a non-WP platform with its own API

### ISSUE THREAD

**Issue by jan1980** [kloon/WooCommerce-REST-API-Client-Library#54]
Hi guys, I'm a newbie.
I'd like to automatically send all new orders to a third party website with its own API, where they would process them.

In my case, it's scalablepress.com. On their docs, they ask for this format to accept a given order:

```
POST https://api.scalablepress.com/v2/order

    EXAMPLE REQUEST

curl "https://api.scalablepress.com/v2/order" \
  -u ":f8a2262aa5285c2050e435c5e581cb0c" \
  -d "orderToken=c6ae6ca449719e5237d103139255ecdd"

    EXAMPLE RESPONSE

{
  "total": 202.79,
  "shipping": 10.80,
  "subtotal": 191.99,
  "orderToken": "c6ae6ca449719e5237d103139255ecdd",
  "createdAt": "2014-08-15T01:46:02.035Z",
  "events": [
    {
      "name": "quote",
      "description": "Quote completed",
      "createdAt": "2014-08-15T01:46:02.036Z"
    },
    {
      "name": "order",
      "description": "Order placed. Processing",
      "createdAt": "2014-08-15T05:50:07.300Z"
    }
  ],
  "items": [
    {
      "type": "dtg",
      "designId": "53ed3a23b3730f0e27a66514",
      "address": {
        "name": "My Customer",
        "address1": "123 Scalable Drive",
        "city": "West Pressfield",
        "state": "CA",
        "zip": "12345",
        "country": "US"
      },
      "products": [
        {
          "productId": "gildan-sweatshirt-crew",
          "color": "ash",
          "quantity": 12,
          "size": "lrg"
        }
      ],
      "designUrl": "https://api.scalablepress.com/v2/design/53ed3a23b3730f0e27a66514"
    }
  ],
  "orderId": "53ed665ab3730f0e27a66516",
  "mode": "test"
}
```

Is there a chance for me to make the WooCommerce orders to be formatted that way, and to be automatically sent to them?

Many thanks for your help,
Jan

**Comment by maxrice** [comment]
It might be easier to use the [XML Exporter](http://www.woothemes.com/products/customerorder-xml-export-suite/) which already handles the automatic export + POSTing to do the heavy lifting and use the [output filters](http://docs.woothemes.com/document/woocommerce-customer-order-xml-export-suite-developer-documentation/#section-3) to simply change the data into the JSON format required :smile:

**Comment by jan1980** [comment]
Hi Max many thanks, I'll take a look at it and will report back.Thanks!

**Comment by oBigZee** [comment]
Hey,

Not sure if you still need this, but if you aren't willing to pay the $100 for the Order XML Export Suite, you can use the woocommerce API, and then the get_orders() methods to go through all your orders and generate the JSON you need, then post it. It is a little more complicated, but if you're willing to get your hands dirty, you can save $100.

**Comment by bryceadams** [comment]
@jan1980 you could just use webhooks for this (new settings tab in 2.3) or the API to programatically create a webhook.
