### ISSUE TITLE
Update status for order

### ISSUE THREAD

**Issue by man-vnosc** [kloon/WooCommerce-REST-API-Client-Library#57]
$wc_api = new WC_API_Client(self::CONSUMER_KEY, self::CONSUMER_SECRET, self::STORE_URL);
$wc_api->update_order( 356, $data = array( 'status' => 'processing', 'note' => 'This is a note') );

I can't update status for order. Although, I can get list orders. Please help me.

**Comment by IcuScc** [comment]
Hi. in V2 doesn't works. in V1 works OK. 
For update my order status a using V1

**Comment by uresh** [comment]
its not working i used ver
/**
 * WooCommerce API Client Class
 *
 * @author Gerhard Potgieter
 * @since 2013.12.05
 * @copyright Gerhard Potgieter
 * @version 0.3.1
 * @license GPL 3 or later http://www.gnu.org/licenses/gpl.html
 */
insted of updating its create new order

**Comment by maxrice** [comment]
in v2:

`$client->orders->update_status( $order_id, $status )`

**Comment by jensdeschrijver** [comment]
Hi

I'm using the latest version of the your PHP library. The function $client->orders->update_status($order_id, 'completed'), witch updates the status to completed, doesn't work. 
It returns the following error: 

Invalid JSON returned for http://.../wc-api/v2/orders/102?oauth_consumer_key=...&oauth_timestamp=...&oauth_nonce=...&oauth_signature_method=HMAC-SHA256&oauth_signature=...

Somebody to help?
