### ISSUE TITLE
Create Products

### ISSUE THREAD

**Issue by IcuScc** [kloon/WooCommerce-REST-API-Client-Library#58]
Hi,
I want to create & update products (simples or with variations)
have anybody an example?

Thanks a lot

**Comment by rodolfojnn** [comment]
Hi, I made an implementation that works fine. 

Change the API_ENDPOINT to 'wc-api/v2/';

In class-wc-api-client, add:

/**
         * Update a product by id
         * @param int $product_id
         * @param array $data
         * @param string $method
         * @return type
         */
        public function update_product($product_id, $data, $method="PUT") {
            return $this->_make_api_call( 'products/' . $product_id, ['product'=>$data], $method );
        }

In method query in _make_api_call function, add:

if ( 'PUT' === $method ) {
            curl_setopt( $ch, CURLOPT_CUSTOMREQUEST, 'PUT' );
            curl_setopt( $ch, CURLOPT_POSTFIELDS, json_encode( $params ) );  
}

Usage:
$this->wc_api->update_product( $_i->web_id, $data );

**Comment by IcuScc** [comment]
Thank you @rodolfojnn 
I'll try it and i say you the result of my test.

another question, your example is for update and create? or only for update?

Thanks

**Comment by rodolfojnn** [comment]
Only for update a item by ID. 

To create, you have to send a POST into  endpoint/products.

public function create_product($data, $method="POST") {
    return $this->_make_api_call( 'products/', ['product'=>$data], $method );
}

I'm not try this, but I think it works. 

Thx

**Comment by IcuScc** [comment]
Hi. @rodolfojnn 
update works ok. i have to make several test again, but with simple product works ok.

i must to have this change

return $this->_make_api_call( 'products/' . $product_id, ['product'=>$data], $method );
for
return $this->_make_api_call( 'products/' . $product_id, array('product'=>$data), $method );

i add this function to create product
public function create_producto($data) 
{
	return $this->_make_api_call( 'products/' , array('product'=>$data), 'POST' );
}

but i retrieve this message
{"errors":[{"code":"woocommerce_api_authentication_error","message":"Firma incorrecta - no coindicen las firmas"}

do you know why??

**Comment by jogeshpi03** [comment]
Hi there, 
Same problem am getting to create product that generates this error: 

```{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}

**Comment by Dewilas** [comment]
i got same error

**Comment by mdorchain** [comment]
I get the same issue on both branches I tested, just can't create products :(

**Comment by sudhirmishra** [comment]
For all those having the Invalid Signature error, it is explained over here https://github.com/woothemes/woocommerce/issues/7833 along with a fix.

**Comment by maxrice** [comment]
in v2:

```php
$client->products->create( array( 'title' => 'Product Title' ) );
$client->products->update( $product_id, array( 'title' => 'New Product Title' ) );
```

you can see the full list of product params here: http://woothemes.github.io/woocommerce-rest-api-docs/#products-properties

**Comment by IcuScc** [comment]
Hi Max, thank you

how do you create $client var?

dont works for me.

thanks again.

**Comment by maxrice** [comment]
download the latest version and follow try [example.php](https://github.com/kloon/WooCommerce-REST-API-Client-Library/blob/master/example/example.php) :)

**Comment by IcuScc** [comment]
Thanks max.. 
I download your example, and the latest version of woocomerce. I go to try now.
your lib/woocommerce-api.php is yours or is a part of woocommerce?

can you share your lib/woocommerce-api.php??  :-)

**Comment by IcuScc** [comment]
Max. i found your git
https://github.com/kloon/WooCommerce-REST-API-Client-Library

i try it

thanks a lot

**Comment by IcuScc** [comment]
Max. All works OK.
Thank you very much.
