### ISSUE TITLE
v2 Oauth2 authentication?

### ISSUE THREAD

**Issue by peardox** [kloon/WooCommerce-REST-API-Client-Library#62]
I've talked to a few people about this and the ingrained argument against it is that you need SSL

Someone who provides a service will happily pay the bux for a CERT

If you look @ Shopify they have a marketplace for integrations to third parties (I've got a Shopify integration that works anonymously as an "App")

At present I need to get the API codes to integrate Woo, much preferable is a Oauth2 handshake so we can publish our integration platform

This is not only good for me, it helps Woo become a proper competitor with Shopify

See http://docs.shopify.com/api for their stuff

**Comment by maxrice** [comment]
@peardox Yeah OAuth2 does require SSL -- that said, there's an open issue on the WC repository for making it easier for 3rd party applications to have users authenticate with an app and get API keys. see https://github.com/woothemes/woocommerce/issues/6930
