### ISSUE TITLE
how do I show my WooCommerce products to another website HELPPP?

### ISSUE THREAD

**Issue by d00nn1** [kloon/WooCommerce-REST-API-Client-Library#66]
Hello everybody, I have a big ask.
How can I get my products in another web integrate the displayed even there I've read everything 10 times and I'm just not on.
I ask everyone if anyone can help me please helpp.

**Comment by WPprodigy** [comment]
Hi d00nn1, 

I just developed a pretty simple shortcode system that will allow you to do this. It's still in it's testing stages, but you should find it fully functional. 

You can view and download the plugin here: https://github.com/WPprodigy/woocommerce-external-product-embed

Hope this helps!
