### ISSUE TITLE
how to return error

### ISSUE THREAD

**Issue by Dewilas** [kloon/WooCommerce-REST-API-Client-Library#67]
hello,

i need return error on login $wc_api = new WC_API_Client( $consumer_key, $consumer_secret, $store_url );

if incorrect url - return string or incorrect key return string. now error returning than i do _make_api_call method, but i need than im creating the object

**Comment by kloon** [comment]
@Dewilas you will need to make a call to an endpoint to see if the login details are correct, so after running the class creation code, do a $wc_api-> get_order( 1 ) call and it will return an error if authentication failed.

**Comment by Dewilas** [comment]
thanks it works
