### ISSUE TITLE
Connecting to REST API v2 with java is throwing error that signature not match.

### ISSUE THREAD

**Issue by gopalsingh462** [kloon/WooCommerce-REST-API-Client-Library#68]
Here is my java code.
	private static final String ARG_SECTION_NUMBER = "section_number";
		private static final String CONSUMERKEY = "ck_cfaf32e212c68c7c66b9a8f43625af72";
		private static final String CONSUMERSECRET = "cs_814f422a33bc737d188cb6a05ea4897c";
		private static final String METHOD = "HMAC-SHA1";
		private static final String URL = "http://192.168.1.21/wordpress/wc-api/v2/orders";
		private static final String PARAMNAME_KEY = "oauth_consumer_key";
		private static final String PARAMNAME_SECRET = "oauth_consumer_secret";
		private static final String PARAMNAME_NONCE = "oauth_nonce";
		private static final String PARAMNAME_TIMESTAMP = "oauth_timestamp";
		private static final String PARAMNAME_SIGNATURE = "oauth_signature";
		private static final String PARAMNAME_SIGNATURE_METHOD = "oauth_signature_method";

class TestApi extends AsyncTask<Void, Void, Void> {
			ProgressDialog d;
			JSONParser jparser = new JSONParser();
			JSONObject response;
			List<NameValuePair> parameters;

			@Override
			protected Void doInBackground(Void... params) {
				parameters = new ArrayList<NameValuePair>();

				parameters.add(new BasicNameValuePair("oauth_consumer_key",
						CONSUMERKEY));
				parameters.add(new BasicNameValuePair("oauth_consumer_secret",
						CONSUMERSECRET));
				parameters.add(new BasicNameValuePair("oauth_timestamp", System
						.currentTimeMillis() / 1000 + ""));
				parameters.add(new BasicNameValuePair("oauth_nonce",
						"sdfasdfasdfasdfsdfsdf"));
				parameters.add(new BasicNameValuePair("oauth_signature_method",
						"HMAC-SHA1"));
				String encoded_base_url = "GET&" + URLEncoder.encode(URL) + "&";
				Log.d("encoded url", encoded_base_url);
				StringBuilder builder = new StringBuilder();
				builder.append(PARAMNAME_KEY + "=" + CONSUMERKEY + "&");
				builder.append(PARAMNAME_SECRET + "=" + CONSUMERSECRET + "&");
				builder.append(PARAMNAME_TIMESTAMP + "="
						+ System.currentTimeMillis() / 100 + "&");
				builder.append(PARAMNAME_NONCE + "="
						+ "sdfdsfsdfsdfsdfsdfsdfsdfsdfsefsdsdf" + "&");
				builder.append(PARAMNAME_SIGNATURE_METHOD + "=" + METHOD);
				String str = builder.toString();
				str = URLEncoder.encode(str);
				Log.d("prepared string", str);
				String signature = encoded_base_url + str;
				String encoded = "";
				try {
					Mac mac = Mac.getInstance(METHOD);
					byte[] key = CONSUMERSECRET.getBytes("utf-8");
					SecretKey secretKey = new SecretKeySpec(key, METHOD);
					mac.init(secretKey);
					byte[] signaturebytes = mac.doFinal(signature
							.getBytes("utf-8"));
					encoded = Base64.encodeToString(signaturebytes, Base64.DEFAULT);
				} catch (NoSuchAlgorithmException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (InvalidKeyException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (UnsupportedEncodingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				Log.d("signature", encoded);
				parameters.add(new BasicNameValuePair("oauth_signature",
						encoded));
				response = jparser.makeHttpRequest(URL, "GET", parameters);
				return null;
			}

			@Override
			protected void onPreExecute() {
				// TODO Auto-generated method stub
				super.onPreExecute();
				d = new ProgressDialog(getActivity());
				d.show();
			}

			@Override
			protected void onPostExecute(Void result) {
				// TODO Auto-generated method stub
				super.onPostExecute(result);
				d.dismiss();
				tvResponse.setText(response.toString());
			}

		}
	}

**Comment by kloon** [comment]
Hi @gopalsingh462 

This is not a Java library and the code is not related to the library at all. I suggest you have a look at the WooCommerce code to see how the signature needs to be generated and base you own code on that. Alternatively try and contact WooThemes support for assistance if you are a paying customer of them.
