### ISSUE TITLE
I found WooCommerce Rest Api authentication error .

### ISSUE THREAD

**Issue by Umakant-DM** [kloon/WooCommerce-REST-API-Client-Library#69]
Hi, 

I want to configure WooCommerce Rest API for my website, but when i trying to access products by this url (http://sws.thebluebell.in/wc-api/v2/products) then it will show error .

{"errors":[{"code":"woocommerce_api_authentication_error","message":"oauth_consumer_key parameter is missing"}]}

Please help me.

**Comment by maxrice** [comment]
This error is almost always due to a security plugin (iThemes Security) or `mod_security` running on your hosting provider. Try with the v2 client library and enable `verbose_mode` and re-open this issue if it still persists.

**Comment by MTphilclothier** [comment]
I think I may have the same issue whilst using iThemes Security.  How do I enable verbose_mode? I can't seem to find any reference to this option.

Thanks!

**Comment by baranicse** [comment]
http://localhost/website1/wc-api/v3/customers/email/arun@yopmail.com

"errors": [
        {
            "code": "woocommerce_api_authentication_error",
            "message": "oauth_consumer_key parameter is missing"
        }
    ]
}

i got this error while using woocommerce in postman
