### ISSUE TITLE
ho to create product? have a problem

### ISSUE THREAD

**Issue by Dewilas** [kloon/WooCommerce-REST-API-Client-Library#70]
i got error : 
ErrorException (E_WARNING)
HELP
rawurldecode() expects parameter 1 to be string, array given

ho to fix it? this is my code:

'public function addProduct($data)
{
    $wc_api = $this->_getClient();

    $newProductData = array(
        'title'             => $data['title'],
        'price'             => $data['price'],
    );

    return $wc_api->create_product($newProductData);
}'

'public function create_product($data, $method = 'POST') {
        	return $this->_make_api_call('products/', ['product' => $data], $method);
    	}'

**Comment by maxrice** [comment]
in v2:

`$client->products->create( array( 'title' => 'Product Title' ) );`

See the full list of product properties here: http://woothemes.github.io/woocommerce-rest-api-docs/#products-properties
