### ISSUE TITLE
WC API found, but JSON is corrupt

### ISSUE THREAD

**Issue by xSinister** [kloon/WooCommerce-REST-API-Client-Library#75]
Hello and thanks for the library!
On the newest version of the library I get this error: 
WC API found, but JSON is corrupt -- ensure the index at "(I've hidden the url)" is valid JSON.

I've tested the JSON at the index in http://jsonlint.com/ and it says it is valid JSON. This only happens for one of the stores I'm using the library for and the store works perfectly on the WooCommerce iPhone app. I might add that the store is in swedish so international letters are common.

Do you have any ideas of what I can do?
Here's some of the error output:
Request:
    [headers] => Array
        (
            [0] => Accept: application/json
            [1] => Content-Type: application/json
            [2] => User-Agent: WooCommerce API Client-PHP/2.0.0
        )

Response:
    [code] => 200
    [headers] => Array
        (
            [Server] =>  nginx
            [Date] =>  Wed, 06 May 2015 12:57:43 GMT
            [Content-Type] =>  application/json; charset=UTF-8
            [Content-Length] =>  3854
            [Connection] =>  keep-alive
            [Keep-Alive] =>  timeout=20
            [Expires] =>  Thu, 19 Nov 1981 08:52:00 GMT
            [Pragma] =>  no-cache
            [X-Cacheable] =>  SHORT
            [Vary] =>  Accept-Encoding,Cookie
            [Cache-Control] =>  max-age=600, must-revalidate
            [Accept-Ranges] =>  bytes
            [X-Cache] =>  MISS
            [X-Pass-Why] =>  
            [X-Cache-Group] =>  normal
            [X-Type] =>  default
        )

Thank you for your time!

**Comment by maxrice** [comment]
this is tough to troubleshoot without the API URL, can you post that?

**Comment by maxrice** [comment]
@xSinister try the latest version and let me know if it fixes this issue :)

**Comment by xSinister** [comment]
@maxrice I've tried the new version and it works. :+1:

I found a small bug after the new update, if I use verbose_mode = true and return_as_array = false, this warning pops up: Warning: Creating default object from empty value in class-wc-api-client.php on line 283.

I haven't tried with return_as_array = true.

Thanks for the update!

**Comment by maxrice** [comment]
@xSinister great, I fixed that issue with the warning in SHA: 0736841c0c401af8d4fb07b2f3ba7abbc71602fd if you want to give it another try :)

**Comment by geralt2008** [comment]
Hello and help me, please, I get this error  "WC API found, but JSON is corrupt -- ensure the index at http://iron.toys/wc-api/v2/ is valid JSON. 0". I use 

$options = array(
    'debug' => true,
    'return_as_array' => false,
    'validate_url' => true,
    'timeout' => 30,
    'ssl_verify' => false,
);

**Comment by xSinister** [comment]
Hej, tack f�r ditt mejl. Den 1 oktober 2016 slutade jag min anst�llning p� Tankbar. Ta g�rna kontakt med Philip Saltskog, philip.saltskog@tankbar.com  070-643 79 00.
