### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by maxdiable** [kloon/WooCommerce-REST-API-Client-Library#76]
hi,
i used your library,
but when call any print_r the page show this: 

nvalid JSON returned for http://www.creative-brain.eu/works/test/wc-api/v2/products/count?oauth_consumer_key=ck_d62f3e85d8d86d4b479c8dd8a54dd58c&oauth_timestamp=1430920132&oauth_nonce=7024c7e96785fd0df9824211a62a216d130a3419&oauth_signature_method=HMAC-SHA256&oauth_signature=wUyWVRMKmoFGhb1m5W6LKgyKBVhCvW95g53JjlDbNWQ%3D. 404 stdClass Object ( [headers] => Array ( [0] => Accept: application/json [1] => Content-Type: application/json [2] => User-Agent: WooCommerce API Client-PHP/2.0.0 ) [method] => GET [url] => http://www.creative-brain.eu/works/test/wc-api/v2/products/count?oauth_consumer_key=ck_d62f3e85d8d86d4b479c8dd8a54dd58c&oauth_timestamp=1430920132&oauth_nonce=7024c7e96785fd0df9824211a62a216d130a3419&oauth_signature_method=HMAC-SHA256&oauth_signature=wUyWVRMKmoFGhb1m5W6LKgyKBVhCvW95g53JjlDbNWQ%3D [params] => Array ( [oauth_consumer_key] => ck_d62f3e85d8d86d4b479c8dd8a54dd58c [oauth_timestamp] => 1430920132 [oauth_nonce] => 7024c7e96785fd0df9824211a62a216d130a3419 [oauth_signature_method] => HMAC-SHA256 [oauth_signature] => wUyWVRMKmoFGhb1m5W6LKgyKBVhCvW95g53JjlDbNWQ= ) [data] => Array ( ) [body] => [duration] => 0.62004 ) stdClass Object ( [body] =>

any help ?

br

Max

**Comment by maxrice** [comment]
Is the `body` property empty or did the text you pasted get cut off? Check your server error logs, as it could've thrown a fatal error and returned an empty body for that request.

**Comment by maxrice** [comment]
@maxdiable try the latest version and let me know if it resolves this

**Comment by maxdiable** [comment]
ok, 
i test your last version.

br

max

**Comment by maxdiable** [comment]
hi, i tested your last version but not working.
the result is:

Invalid JSON returned for http://www.creative-brain.eu/works/test/wc-api/v2/products/categories?oauth_consumer_key=ck_d62f3e85d8d86d4b479c8dd8a54dd58c&amp;oauth_timestamp=1430983701&amp;oauth_nonce=4a74126f3c84286254c8df3eef49d8f175d15538&amp;oauth_signature_method=HMAC-SHA256&amp;oauth_signature=1s%2FfHDHZvi%2Bc%2ByKa%2FF8FOUzpMq2cdYDjTEyuBc3VkeM%3D.
404
stdClass Object
(
    [headers] =&gt; Array
        (
            [0] =&gt; Accept: application/json
            [1] =&gt; Content-Type: application/json
            [2] =&gt; User-Agent: WooCommerce API Client-PHP/2.0.0
        )

    [method] =&gt; GET
    [url] =&gt; http://www.creative-brain.eu/works/test/wc-api/v2/products/categories?oauth_consumer_key=ck_d62f3e85d8d86d4b479c8dd8a54dd58c&amp;oauth_timestamp=1430983701&amp;oauth_nonce=4a74126f3c84286254c8df3eef49d8f175d15538&amp;oauth_signature_method=HMAC-SHA256&amp;oauth_signature=1s%2FfHDHZvi%2Bc%2ByKa%2FF8FOUzpMq2cdYDjTEyuBc3VkeM%3D
    [params] =&gt; Array
        (
            [oauth_consumer_key] =&gt; ck_d62f3e85d8d86d4b479c8dd8a54dd58c
            [oauth_timestamp] =&gt; 1430983701
            [oauth_nonce] =&gt; 4a74126f3c84286254c8df3eef49d8f175d15538
            [oauth_signature_method] =&gt; HMAC-SHA256
            [oauth_signature] =&gt; 1s/fHDHZvi+c+yKa/F8FOUzpMq2cdYDjTEyuBc3VkeM=
        )

    [data] =&gt; Array
        (
        )

    [body] =&gt; 
    [duration] =&gt; 0.8203
)
stdClass Object
(
    [body] =&gt; 


br

Max

**Comment by stevecove** [comment]
Having the same issue - working fine locally, fails on live server. Same empty response body in the expection message. Copying the url from the exception message into a browser address bar returns valid json.

I have checked that curl is enabled on the live server. Not seeing anything in the error logs either, not sure what to try next.

**Comment by stevecove** [comment]
Ok, further debuuging, setting the `validate_url` flag results in the following:

`
WC API found, but JSON is corrupt -- ensure the index at http://thatsbrave-dev.co.uk/***/wc-api/v2/ is valid JSON.` 

However visiting the url in question produces valid json ( to check replace *** with `mongrelcroc`) Something is wrong with the http request, not sure what though

**Comment by xSinister** [comment]
@stevecove I had the same exact bug yesterday but @maxrice fixed it with the newest version. Have you tried to download the update from a couple hours back? For me it was because of some bad characters added to the index, which @maxrice assumed was because of either the theme or a plugin.

**Comment by stevecove** [comment]
Thanks @xSinister, however my issue (and probably @maxdiable 's ) is the curl request itsself not returning any data, rather than the json parsing.

**Comment by stevecove** [comment]
Just a followup, this appears to be an issue when attempting to access a url on the same domain as the code is running, eg if i change the url to another woocommerce site, all is correct (well auth fails, but thats not the point). Also, a regular curl request / file_get_contents call to the same domain fails, so the issue is likely a hosting one, not anything specific to this api wrapper. For reference i am having this issue with a HeartInternet resellers account. Will update when i hear back from their customer support

**Comment by maxdiable** [comment]
ok ..tanks stevecove..

**Comment by maxrice** [comment]
@stevecove tested your site on my end and the index works properly with the latest version :) I suspect the host may be blocking HTTP requests made from the server the site is hosted on for security reasons.

@maxdiable this is a PHP library, so if you need to get products from inside your Android app, you'll need to develop a Java library that works on Android, see http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by stevecove** [comment]
@maxrice yes, you are correct. I suspected as much as soon as i realized regular curl calls failed. This has now been confirmed by the host. Probably going to be easier to move hosts that abandon the api.

**Comment by maxdiable** [comment]
hi,
now i speaking with provider..  there have changed the htaccess and now the error is:

<body>Invalid JSON returned for http://woocommerce.creative-brain.eu/wc-api/v2/products/count?oauth_consumer_key=ck_2552853ff4476d65dbd03ece58bec8a1&amp;oauth_timestamp=1431345317&amp;oauth_nonce=f5a2b054709da13beec5f013069281a4933ae9dd&amp;oauth_signature_method=HMAC-SHA256&amp;oauth_signature=TheuFOCz5MsDu5pv2pTW7mmZawYKllqU7zk%2FB7GRzIo%3D.
301
stdClass Object
(
    [headers] =&gt; Array
        (
            [0] =&gt; Accept: application/json
            [1] =&gt; Content-Type: application/json
            [2] =&gt; User-Agent: WooCommerce API Client-PHP/2.0.0
        )

    [method] =&gt; GET
    [url] =&gt; http://woocommerce.creative-brain.eu/wc-api/v2/products/count?oauth_consumer_key=ck_2552853ff4476d65dbd03ece58bec8a1&amp;oauth_timestamp=1431345317&amp;oauth_nonce=f5a2b054709da13beec5f013069281a4933ae9dd&amp;oauth_signature_method=HMAC-SHA256&amp;oauth_signature=TheuFOCz5MsDu5pv2pTW7mmZawYKllqU7zk%2FB7GRzIo%3D
    [params] =&gt; Array
        (
            [oauth_consumer_key] =&gt; ck_2552853ff4476d65dbd03ece58bec8a1
            [oauth_timestamp] =&gt; 1431345317
            [oauth_nonce] =&gt; f5a2b054709da13beec5f013069281a4933ae9dd
            [oauth_signature_method] =&gt; HMAC-SHA256
            [oauth_signature] =&gt; TheuFOCz5MsDu5pv2pTW7mmZawYKllqU7zk/B7GRzIo=
        )

    [data] =&gt; Array
        (
        )

    [body] =&gt; 
    [duration] =&gt; 0.55428
)
stdClass Object
(
    [body] =&gt; 
    [code] =&gt; 301
    [headers] =&gt; Array
        (
            [Date] =&gt;  Mon, 11 May 2015 11:55:17 GMT
            [Server] =&gt;  Apache
            [X-Powered-By] =&gt;  PHP/5.5.24
            [X-Pingback] =&gt;  http://woocommerce.creative-brain.eu/xmlrpc.php
            [Location] =&gt;  http://woocommerce.creative-brain.eu/wc-api/v2/products/count/?oauth_consumer_key=ck_2552853ff4476d65dbd03ece58bec8a1&amp;oauth_timestamp=1431345317&amp;oauth_nonce=f5a2b054709da13beec5f013069281a4933ae9dd&amp;oauth_signature_method=HMAC-SHA256&amp;oauth_signature=TheuFOCz5MsDu5pv2pTW7mmZawYKllqU7zk%2FB7GRzIo%3D
            [Content-Length] =&gt;  0
            [Content-Type] =&gt;  text/html; charset=UTF-8
        )

)
</body>

any help ?

Max

**Comment by maxrice** [comment]
@maxdiable I tested the URL with the latest version and it works properly :) try [downloading it](https://github.com/kloon/WooCommerce-REST-API-Client-Library/archive/master.zip) and see if it works for you

**Comment by maxdiable** [comment]
good :) tanks..
very nice :)

**Comment by maxdiable** [comment]
thanks for the great explanation , I just want to know how to extract the information that I get from the web service . 
In fact, using the library made ​​me get a string like this:

stdClass Object ( [count] => 1 [http] => stdClass Object ( [request] => stdClass Object ( [headers] => Array ( [0] => Accept: application/json [1] => Content-Type: application/json [2] => User-Agent: WooCommerce API Client-PHP/2.0.0 ) [method] => GET [url] => http://woocommerce.creative-brain.eu/wc-api/v2/products/count?oauth_consumer_key=ck_2552853ff4476d65dbd03ece58bec8a1&oauth_timestamp=1431502258&oauth_nonce=aed5e856056d8f2fdbe49b58fe168976631e480e&oauth_signature_method=HMAC-SHA256&oauth_signature=0TiBdt1xKFHmn6Ek3UvyzmYTXZWaRhtzhOYL9a2hmK4%3D [params] => Array ( [oauth_consumer_key] => ck_2552853ff4476d65dbd03ece58bec8a1 [oauth_timestamp] => 1431502258 [oauth_nonce] => aed5e856056d8f2fdbe49b58fe168976631e480e [oauth_signature_method] => HMAC-SHA256 [oauth_signature] => 0TiBdt1xKFHmn6Ek3UvyzmYTXZWaRhtzhOYL9a2hmK4= ) [data] => Array ( ) [body] => [duration] => 1.93458 ) [response] => stdClass Object ( [body] => {"count":1} [code] => 200 [headers] => Array ( [Date] => Wed, 13 May 2015 07:30:58 GMT [Server] => Apache [X-Powered-By] => PHP/5.3.29 [Transfer-Encoding] => chunked [Content-Type] => application/json; charset=UTF-8 ) ) ) )

how do I get only the information "count" from this string???

br

Massimo

**Comment by maxrice** [comment]
```php
$data = $client->products->get_count();
echo $data->count;
```

**Comment by maxdiable** [comment]
Very nove. 
Tanks

Max

**Comment by Xmenas** [comment]
I got same problem. My code:

	require_once('restAPI/lib/woocommerce-api.php' );

	$options = array(
		'debug'           => true,
		'return_as_array' => false,
		'validate_url'    => false,
		'timeout'         => 30,
		'ssl_verify'      => true,
	);

	try {

		$consumer_key = 'ck_fe28043f50053f8a3fbefa54b014385615711d20'; // Add your own Consumer Key here
		$consumer_secret = 'cs_70208c940d330a8e7487c9be9145198a831a368d'; // Add your own Consumer Secret here
    
		$client = new WC_API_Client( 'https://printify.lt', $consumer_key, $consumer_secret, $options );
				
		print_r($client->orders->get());
		
	} catch ( WC_API_Client_Exception $e ) {

		echo $e->getMessage() . PHP_EOL;
		echo $e->getCode() . PHP_EOL;

		if ( $e instanceof WC_API_Client_HTTP_Exception ) {

			print_r( $e->get_request() );
			print_r( $e->get_response() );
		}
	}
And i get error:

Invalid JSON returned for https://printify.lt/wc-api/v2/orders?consumer_key=ck_fe28043f50053f8a3fbefa54b014385615711d20&consumer_secret=cs_70208c940d330a8e7487c9be9145198a831a368d. 0 stdClass Object ( [headers] => Array ( [0] => Accept: application/json [1] => Content-Type: application/json [2] => User-Agent: WooCommerce API Client-PHP/2.0.1 ) [method] => GET [url] => https://printify.lt/wc-api/v2/orders?consumer_key=ck_fe28043f50053f8a3fbefa54b014385615711d20&consumer_secret=cs_70208c940d330a8e7487c9be9145198a831a368d [params] => Array ( [consumer_key] => ck_fe28043f50053f8a3fbefa54b014385615711d20 [consumer_secret] => cs_70208c940d330a8e7487c9be9145198a831a368d ) [data] => Array ( ) [body] => [duration] => 0.03939 ) stdClass Object ( [body] => [code] => 0 [headers] => Array ( ) )

**Comment by itzRamkumar** [comment]
Hi,
How to get the Particular Customer order using that Customer API key.. When i am using the customer Api key it doesn't show anything if i use the Administrator Api key it will show the entire Orders. now i run locally and also i get error like  

Fatal error: Uncaught exception 'WC_API_Client_HTTP_Exception' with message 'Invalid JSON returned for http://localhost/...

 Help me. 

Thanks in Advance

**Comment by azizchouhan** [comment]
Well, when you will change your permalink settings , Plain to Post name, this error will disappear.

so change your site's permalink setting, dont use default setting
