### ISSUE TITLE
get_by_sku

### ISSUE THREAD

**Issue by uresh** [kloon/WooCommerce-REST-API-Client-Library#77]
when i try to get product using sku like "cam-7000"  it treturn error,but it works when i remove - like  this"cam7000" . 
$client->products->get_by_sku( 'cam-7000' ) )

**Comment by maxrice** [comment]
enable `debug` and post the request/response here with the store URL redacted :)

**Comment by uresh** [comment]
here is the error -
Error: No route was found matching the URL and request method [woocommerce_api_no_route] 404 stdClass Object ( [headers] => Array ( [0] => Accept: application/json [1] => Content-Type: application/json [2] => User-Agent: WooCommerce API Client-PHP/2.0.0 ) [method] => GET [url] => http://localhost/wordpress/wc-api/v2/products/sku/cam-7000?oauth_consumer_key=ck_2d3f8147ad53f7aba688987782d59656&oauth_timestamp=1431950089&oauth_nonce=b2bf012eef4fcd0e7ab53be087fbcb95eb6e11d7&oauth_signature_method=HMAC-SHA256&oauth_signature=90W9ip8wk1ZwEK%2BPP%2BXiL3jHh8d8bSW0YeyrZ1wzdWs%3D [params] => Array ( [oauth_consumer_key] => ck_2d3f8147ad53f7aba688987782d59656 [oauth_timestamp] => 1431950089 [oauth_nonce] => b2bf012eef4fcd0e7ab53be087fbcb95eb6e11d7 [oauth_signature_method] => HMAC-SHA256 [oauth_signature] => 90W9ip8wk1ZwEK+PP+XiL3jHh8d8bSW0YeyrZ1wzdWs= ) [data] => [body] => [duration] => 13.733 ) stdClass Object ( [body] => {"errors":[{"code":"woocommerce_api_no_route","message":"No route was found matching the URL and request method"}]} [code] => 404 [headers] => Array ( [Date] => Mon, 18 May 2015 11:54:49 GMT [Server] => Apache/2.4.9 (Win32) PHP/5.5.12 [X-Powered-By] => PHP/5.5.12 [Content-Length] => 115 [Content-Type] => application/json; charset=UTF-8 ) )

**Comment by maxrice** [comment]
Ah yeah, the issue is the SKU with dashes in it, see https://github.com/woothemes/woocommerce/issues/8179#issuecomment-102870334

When WC 2.4 is released, the get by SKU method will be updated to use the upcoming query string filter instead.

**Comment by uresh** [comment]
thanks
