### ISSUE TITLE
Get orders by status using example doesn't work.

### ISSUE THREAD

**Issue by chaosratt** [kloon/WooCommerce-REST-API-Client-Library#78]
The readme indicates that using "$client->orders->get( array( 'status' => 'completed' ) ) " will return all orders with the status completed, however I get an error:

Error: No route was found matching the URL and request method [woocommerce_api_no_route]

looking over the debug, the url sent is:

http://www.site.com/wc-api/v2/orders/completed?oauth_consumer_key=/super secret stuff here/

Looking over other examples, it appears this is the correct url syntax, and does work with a straight curl request:

https://www.site.com/wc-api/v2/orders/?status=completed

Editing class-wc-api-client-authentication.php, ~ line 55, adding:
'status'	=> 'completed',
Has the desired effect.

**Comment by maxrice** [comment]
Sorry about that, it was a typo in the readme. Fixed with SHA: ba25be888eaee105170955f6d80743b5ff88fc36

you'll want to do `$client->order->get( null, array( 'status' => 'completed ' ) );` :smile_cat:

**Comment by chaosratt** [comment]
Beautiful, thanks.
Also, you made another typo. Should be $client->order**s**->get, not $client->order->get

**Comment by maxrice** [comment]
fixed my comment, thanks :)
