### ISSUE TITLE
Product Delete

### ISSUE THREAD

**Issue by macmedia** [kloon/WooCommerce-REST-API-Client-Library#79]
Product deletion is not working for me when passing the product_id and false. I added an else statement (line 83) to abstract-wc-api-client-resource.php / set_request_args so the the required "force" param is added to the url.

`$c = $client->products->delete($product_id, false);`

    // convert bool true to string 'true', required for DELETE endpoints
    if ( isset( $this->request_params['force'] ) && $this->request_params['force'] ) {
         $this->request_params['force'] = 'true';
    }elseif ( isset( $this->request_params['force'] ) && !$this->request_params['force'] ){
         $this->request_params['force'] = 'false';
    }

added: ` $this->request_params['force'] = 'false';` to make sure a ?force=false is added to the url. Was I doing something wrong?

**Comment by maxrice** [comment]
Setting `force = false`, or omitting the `force` query parameter will trash the product instead of deleting it permanently. If you want to permanently delete, set `force = true` :)
