### ISSUE TITLE
cURL HTTP error 100

### ISSUE THREAD

**Issue by Dewilas** [kloon/WooCommerce-REST-API-Client-Library#80]
hello,

i got api error: cURL HTTP error 100

than creating product with many variants about 40. what is indicate and how to fix what?

**Comment by Dewilas** [comment]
problem solved: it was timeout

		curl_setopt( $ch, CURLOPT_CONNECTTIMEOUT, 300 );
	        curl_setopt( $ch, CURLOPT_TIMEOUT, 300 );

**Comment by maxrice** [comment]
@Dewilas FYI you can use the `timeout` setup option to set a cURL timeout without modifying the lib code :)

**Comment by Dewilas** [comment]
thanks @maxrice but i work with your old source :) can u help me, how to add products attributes via API like color and size?

i mean in woocoomerce: Products-> Attributes

**Comment by maxrice** [comment]
I don't believe 2.3 supports adding product attributes, but 2.4 will -- check out https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L74-L85
