### ISSUE TITLE
Cannot Find woothemes/woocommerce-api in Packagist

### ISSUE THREAD

**Issue by nandinibhaduri** [kloon/WooCommerce-REST-API-Client-Library#81]
Looks like the package has been change to make it a composer package. But I cannot find the package in Packagist.

**Comment by GaryPEGEOT-WIC** [comment]
Each class will also need a proper namespace to be usable via Composer / PHP Frameworks

**Comment by judgej** [comment]
@GaryPEGEOT-WIC I've created a pull request that will allow it to work in composer without namespaces. Namespaces are definitely the *the* ultimate way to go, but this package does work with composer without namespaces.

**Comment by judgej** [comment]
@GaryPEGEOT-WIC  raised issue #85 to suggest moving on from PHP 5.2, so namespaces can be introduced.

**Comment by maxrice** [comment]
I'll add this to Packagist after #84 is merged :)

**Comment by judgej** [comment]
Even if it's not complete, people are fine with that. If it's there, it gets eyeballs, and that will help it move forward. People are already putting their own forks on there:

https://packagist.org/packages/wic/woocommerce-api

That particular one is going off in a namespaced direction, so there is some differentiation there.

This one is a very old fork of yours from API v1 days by the looks of it:

https://packagist.org/packages/afurculita/woocommerce-api-client

So make it clear in the description what is special about this version for user of packageist (this a particular bugbear of mine when people don't do that, and packageist has a dozen versions of essentially the same package and you have no idea which is being maintained/customised for a special purpose/going off in a different direction/etc).

Tell me if I'm teaching granny to suck eggs ;-) I kind of have one foot in the WP world and the other in the composer/PSR world, and up until now they have been very separate, with different approaches to many coding problems.

**Comment by maxrice** [comment]
added: https://packagist.org/packages/woothemes/woocommerce-api

thanks all :)
