### ISSUE TITLE
Get orders for a given customer

### ISSUE THREAD

**Issue by arindamgit** [kloon/WooCommerce-REST-API-Client-Library#82]
I have tried the following
a) $client->orders->get(null, array('customer_id' => '3'))
b) $client->orders->get(null, array(filter['customer_id'] => '3'))
c) $client->orders->get(array(filter['customer_id'] => '3'))

a) and b) return all orders rather than for a specific customer
c) throws errors

Will you tell me what is the right way to do this

Thanks in advance

**Comment by arindamgit** [comment]
Ok I now know. customer_id is not a valid filter, its not your fault. But I am like duh on the woo API.

**Comment by maxrice** [comment]
try `$client->customers->get_orders( $customer_id );`
