### ISSUE TITLE
Update PHP version requirement?

### ISSUE THREAD

**Issue by judgej** [kloon/WooCommerce-REST-API-Client-Library#85]
I have noticed a few PRs are already starting to use namespaces, though the core package isn't. PHP5.2 is dead, dead, dead, regardless of what the WP project seems to think - it is beyond irresponsible to keep supporting it and implicitly discouraging people from upgrading.

So, any plans to move on to support later versions of PHP? Bringing in PHP 5.3 namespaces at a very minimum would be a great boost to interoperability. PHP 5.4 would be better, but even that is coming to end-of-life.

**Comment by kloon** [comment]
@judgej I understand 5.2 is dead and I would fully go with dropping support for it if this library was not used in so many WordPress projects.

Unfortunately a lot of people are using this library as part of WordPress plugins so we need to maintain compatibility for PHP 5.2
