### ISSUE TITLE
Product delete does not work

### ISSUE THREAD

**Issue by orionorigin** [kloon/WooCommerce-REST-API-Client-Library#87]
When i try using the example provided in the library, i get {"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}. Any idea?

**Comment by maxrice** [comment]
This is usually due to a theme or plugin conflict, try deactivating all plugins except WooCommerce on your site and switch to the default theme.

**Comment by maxrice** [comment]
closing for now, feel free to re-open if you find an issue with the library.

**Comment by orionorigin** [comment]
Hello,
Sorry for the late answer.

Theme: Twenty FourteenVersion
Active Plugins: Woocommerce & the plugin which makes the operation.

**Comment by maxrice** [comment]
Hmm, must be a server error then -- are you running nginx or apache?

**Comment by orionorigin** [comment]
apache. The complete trace: 

object(WC_API_Client_HTTP_Exception)[405]
  protected 'request' => 
    object(stdClass)[358]
      public 'headers' => 
        array (size=3)
          0 => string 'Accept: application/json' (length=24)
          1 => string 'Content-Type: application/json' (length=30)
          2 => string 'User-Agent: WooCommerce API Client-PHP/2.0.0' (length=44)
      public 'method' => string 'DELETE' (length=6)
      public 'url' => string 'http://localhost/wp_dev2/wc-api/v2/products/226?force=0&oauth_consumer_key=ck_e6a4077d9b60ff9b62fda1cc255a5ab6&oauth_timestamp=1433957154&oauth_nonce=f09c214841ba68b7e263fad643d4dfbd92c33e86&oauth_signature_method=HMAC-SHA256&oauth_signature=uldTY57pksIPg8OXEx5T9SralC41zlZV3PkLUR%2BzACg%3D' (length=290)
      public 'params' => 
        array (size=6)
          'force' => boolean false
          'oauth_consumer_key' => string 'ck_e6a4077d9b60ff9b62fda1cc255a5ab6' (length=35)
          'oauth_timestamp' => int 1433957154
          'oauth_nonce' => string 'f09c214841ba68b7e263fad643d4dfbd92c33e86' (length=40)
          'oauth_signature_method' => string 'HMAC-SHA256' (length=11)
          'oauth_signature' => string 'uldTY57pksIPg8OXEx5T9SralC41zlZV3PkLUR+zACg=' (length=44)
      public 'data' => 
        array (size=1)
          'force' => boolean false
      public 'body' => null
      public 'duration' => float 15.25805
  protected 'response' => 
    object(stdClass)[357]
      public 'body' => string '{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}' (length=126)
      public 'code' => int 401
      public 'headers' => 
        array (size=5)
          'Date' => string ' Wed, 10 Jun 2015 17:25:54 GMT' (length=30)
          'Server' => string ' Apache/2.2.22 (Win32) PHP/5.3.13' (length=33)
          'X-Powered-By' => string ' PHP/5.3.13' (length=11)
          'Content-Length' => string ' 126' (length=4)
          'Content-Type' => string ' application/json; charset=UTF-8' (length=32)
  protected 'message' => string 'Error: Invalid Signature - provided signature does not match [woocommerce_api_authentication_error]' (length=99)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 401
  protected 'file' => string 'C:\wamp\www\wp_dev\wp-content\plugins\woocommerce-multishop-sync\includes\woocommerce-rest-api\woocommerce-api\class-wc-api-client-http-request.php' (length=147)
  protected 'line' => int 191
  private 'trace' (Exception) => 
    array (size=19)
      0 => 
        array (size=6)
          'file' => string 'C:\wamp\www\wp_dev\wp-content\plugins\woocommerce-multishop-sync\includes\woocommerce-rest-api\woocommerce-api\class-wc-api-client.php' (length=134)
          'line' => int 277
          'function' => string 'dispatch' (length=8)
          'class' => string 'WC_API_Client_HTTP_Request' (length=26)
          'type' => string '->' (length=2)
          'args' => 
            array (size=0)
              ...
      1 => 
        array (size=6)
          'file' => string 'C:\wamp\www\wp_dev\wp-content\plugins\woocommerce-multishop-sync\includes\woocommerce-rest-api\woocommerce-api\resources\abstract-wc-api-client-resource.php' (length=156)
          'line' => int 122
          'function' => string 'make_api_call' (length=13)
          'class' => string 'WC_API_Client' (length=13)
          'type' => string '->' (length=2)
          'args' => 
            array (size=3)
              ...
      2 => 
        array (size=6)
          'file' => string 'C:\wamp\www\wp_dev\wp-content\plugins\woocommerce-multishop-sync\includes\woocommerce-rest-api\woocommerce-api\resources\class-wc-api-client-resource-products.php' (length=162)
          'line' => int 129
          'function' => string 'do_request' (length=10)
          'class' => string 'WC_API_Client_Resource' (length=22)
          'type' => string '->' (length=2)
          'args' => 
            array (size=0)
              ...
      3 => 
        array (size=6)
          'file' => string 'C:\wamp\www\wp_dev\wp-content\themes\twentyfourteen\functions.php' (length=65)
          'line' => int 590
          'function' => string 'delete' (length=6)
          'class' => string 'WC_API_Client_Resource_Products' (length=31)
          'type' => string '->' (length=2)
          'args' => 
            array (size=2)
              ...
      4 => 
        array (size=2)
          'function' => string 'test_rest' (length=9)
          'args' => 
            array (size=3)
              ...
      5 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-includes\shortcodes.php' (length=45)
          'line' => int 286
          'function' => string 'call_user_func' (length=14)
          'args' => 
            array (size=4)
              ...
      6 => 
        array (size=2)
          'function' => string 'do_shortcode_tag' (length=16)
          'args' => 
            array (size=1)
              ...
      7 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-includes\shortcodes.php' (length=45)
          'line' => int 200
          'function' => string 'preg_replace_callback' (length=21)
          'args' => 
            array (size=3)
              ...
      8 => 
        array (size=2)
          'function' => string 'do_shortcode' (length=12)
          'args' => 
            array (size=1)
              ...
      9 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-includes\plugin.php' (length=41)
          'line' => int 213
          'function' => string 'call_user_func_array' (length=20)
          'args' => 
            array (size=2)
              ...
      10 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-includes\post-template.php' (length=48)
          'line' => int 230
          'function' => string 'apply_filters' (length=13)
          'args' => 
            array (size=2)
              ...
      11 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-content\themes\twentyfourteen\content-page.php' (length=68)
          'line' => int 20
          'function' => string 'the_content' (length=11)
          'args' => 
            array (size=0)
              ...
      12 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-includes\template.php' (length=43)
          'line' => int 503
          'args' => 
            array (size=1)
              ...
          'function' => string 'require' (length=7)
      13 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-includes\template.php' (length=43)
          'line' => int 477
          'function' => string 'load_template' (length=13)
          'args' => 
            array (size=2)
              ...
      14 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-includes\general-template.php' (length=51)
          'line' => int 171
          'function' => string 'locate_template' (length=15)
          'args' => 
            array (size=3)
              ...
      15 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-content\themes\twentyfourteen\page-templates\full-width.php' (length=81)
          'line' => int 28
          'function' => string 'get_template_part' (length=17)
          'args' => 
            array (size=2)
              ...
      16 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-includes\template-loader.php' (length=50)
          'line' => int 74
          'args' => 
            array (size=1)
              ...
          'function' => string 'include' (length=7)
      17 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\wp-blog-header.php' (length=37)
          'line' => int 16
          'args' => 
            array (size=1)
              ...
          'function' => string 'require_once' (length=12)
      18 => 
        array (size=4)
          'file' => string 'C:\wamp\www\wp_dev\index.php' (length=28)
          'line' => int 17
          'args' => 
            array (size=1)
              ...
          'function' => string 'require' (length=7)
  private 'previous' (Exception) => null
  public 'xdebug_message' => string '<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> WC_API_Client_HTTP_Exception: Error: Invalid Signature - provided signature does not match [woocommerce_api_authentication_error] in C:\wamp\www\wp_dev\wp-content\plugins\woocommerce-multishop-sync\includes\woocommerce-rest-api\woocommerce-api\class-wc-api-client-http-request.php on line <i>191</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack'... (length=7871)

**Comment by maxrice** [comment]
You'll need to dump the signature produced [here](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-authentication.php#L267) and see how it compares to what the library is generating. You can also look at the `$string_to_sign` and see how that compares. Unfortunately signature errors are fairly difficult to troubleshoot :/

**Comment by orionorigin** [comment]
Ok thanks.

**Comment by pereiradiogo** [comment]
Hi,

I have the same problem! Have a solution?

**Comment by orionorigin** [comment]
No i gave up.

**Comment by pereiradiogo** [comment]
Put in status = trash ;)

**Comment by orionorigin** [comment]
What do you mean?

**Comment by pereiradiogo** [comment]
The best way i found to put the product not visible in the site, was put the status equals to trash

**Comment by orionorigin** [comment]
Oh ok. But me i wanted to empty the trash..

**Comment by pereiradiogo** [comment]
With new version of Woocommerce works!
