### ISSUE TITLE
transaction_id not showing when request get orders

### ISSUE THREAD

**Issue by uresh** [kloon/WooCommerce-REST-API-Client-Library#89]
how to get transaction_id

**Comment by maxrice** [comment]
The WC v2 API doesn't include the transaction ID by default, but you can pass `filter[meta]=true` when retrieving orders to include it.

**Comment by uresh** [comment]
how to pass that is it like that . i tried its not working.
$client->orders->get( null, array('meta'=>true, 'status' => 'completed' ) )

**Comment by maxrice** [comment]
`$client->orders->get( null, array( 'filter[meta]' => true, 'status' => 'completed' ) );`

**Comment by uresh** [comment]
thanks

**Comment by uresh** [comment]
still its not giving id
