### ISSUE TITLE
Creating an order with Pickup Location

### ISSUE THREAD

**Issue by nandinibhaduri** [kloon/WooCommerce-REST-API-Client-Library#90]
Got stuck badly with this. Anyway to create an order using the Rest API with Pick Up Location.

**Comment by nandinibhaduri** [comment]
Actually when I went through the API code for woocommerce I see that the hooks are not being called. The pickup location used in the application I am working has some added plugins. Those are not being called :( Anyone knows any way out? But this is not a issue with this client.

**Comment by maxrice** [comment]
Not every hook would run during an API request, but you could extend the API with a plugin on the client's site to make it possible to add a pickup location.

**Comment by sanojbogoda** [comment]
So isn't this library supports order creation?
