### ISSUE TITLE
how to do the login based on username and password

### ISSUE THREAD

**Issue by abutuffah** [kloon/WooCommerce-REST-API-Client-Library#91]
Hi, I'm planning to develop a woocommerce client site. But the problem is I'm a bit confused of how to authenticate the users by their username/email and password. So there will be login form, and if the login is correct, then I can return the consumer key and secret from the logged in customer and I don't need to generate the keys manual from the profile page at admin.

**Comment by maxrice** [comment]
Something like this was built into WC 2.4, but the library doesn't yet support it -- see https://github.com/woothemes/woocommerce/pull/8021
