### ISSUE TITLE
Trying to create a PHP script for uploading Products

### ISSUE THREAD

**Issue by Soomrojb** [kloon/WooCommerce-REST-API-Client-Library#92]
Hi,

I got data saved in database, what I am trying to do is to retrieve individual data and using the Kloon library for uploading individual records at my WooCommerce shop. I can insert products, categories are okay, tags are fine however I can't add image(s). I am using following code to add products:

$client->products->create(
array( 
'title' => 'Posting through PHP API Library',
'type' => 'simple',
'regular_price' => '9.99',
'in_stock' => 'true',
'status' => 'draft',
'featured' => 'true',
'description' => 'this is a testing product<br>again a testing<br/>third time\nfourth time',
'short_description' => 'Short description for product',
'categories' => array('Africa Region','Algeria'),
'tags' => array('Financial Risk Search','Identity Verification'),
'images' => array(
'src' => 'https://www.mySite.com/wp-content/uploads/2014/04/sc5.jpg',
'position' => '0')
));

If I view product details using same library, it shows:

[images] => Array ( [0] => stdClass Object ( [id] => 0 [created_at] => 2015-06-29T06:33:07Z

The ID of the image is always 0 ([id] => 0), no matter what I do. Kindly help me out, I know I am doing something wrong as I don't see other people reporting same anywhere.

**Comment by maxrice** [comment]
@claudiosmweb any ideas here?

**Comment by claudiosmweb** [comment]
@Soomrojb try this:

```php
$client->products->create( array(
	'title' => 'Posting through PHP API Library',
	'type' => 'simple',
	'regular_price' => '9.99',
	'in_stock' => 'true',
	'status' => 'draft',
	'featured' => 'true',
	'description' => 'this is a testing product
	again a testing
	third time\nfourth time',
	'short_description' => 'Short description for product',
	'categories' => array('Africa Region','Algeria'),
	'tags' => array('Financial Risk Search','Identity Verification'),
	'images' => array(
		array(
			'src' => 'https://www.mySite.com/wp-content/uploads/2014/04/sc5.jpg',
			'position' => '0'
		)
	)
) );
```

**Comment by Soomrojb** [comment]
WoW. Thank you @claudiosmweb, Its working great now!

Thanks a lot!.
