### ISSUE TITLE
Invalid Signature - provided signature does not match

### ISSUE THREAD

**Issue by gtawebb** [kloon/WooCommerce-REST-API-Client-Library#93]
I'm receiving an invalid signature error when trying to connect. I using the example.php code from the examples folder and using:	
print_r( $client->products->get() );

I'm connecting via a REST client calling: http://www.XXX.com/WooCommerce-REST-API-Client-Library-master/example/example.php.

I've tried using both GET and POST.

I'm not using SSL yet, but I get the impression that your API will handle that for me.

Please let me know if you have any ideas? I've commented out any potentially sensitive data with XXX.

Many thanks.

Error: Invalid Signature - provided signature does not match [woocommerce_api_authentication_error]
401

stdClass Object
(
    [headers] => Array
        (
            [0] => Accept: application/json
            [1] => Content-Type: application/json
            [2] => User-Agent: WooCommerce API Client-PHP/2.0.0
        )

    [method] => GET
    [url] => http://www.XXX.com/wc-api/v2/products?oauth_consumer_key=XXX&oauth_timestamp=1435835947&oauth_nonce=XXX&oauth_signature_method=HMAC-SHA256&oauth_signature=XXX
    [params] => Array
        (
            [oauth_consumer_key] => XXX
            [oauth_timestamp] => 1435835947
            [oauth_nonce] => XXX
            [oauth_signature_method] => HMAC-SHA256
            [oauth_signature] =>XXX
        )

    [data] => Array
        (
        )

    [body] => 
    [duration] => 0.6951
)
stdClass Object
(
    [body] => {"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}
    [code] => 401
    [headers] => Array
        (
            [Date] =>  Thu, 02 Jul 2015 11:19:07 GMT
            [Server] =>  Apache
            [X-Powered-By] =>  PHP/5.3.29
            [Connection] =>  close
            [Transfer-Encoding] =>  chunked
            [Content-Type] =>  application/json; charset=UTF-8
        )

)

**Comment by maxrice** [comment]
Signature issues are pretty challenging to troubleshoot, but you can start by disabling all plugins except WC on the site and switching to TwentyTwelve and then testing again. If it works, then there's some conflict with your theme or plugin.

I've also seen an incorrect server time cause this, and an incorrect nginx server configuration. hope this helps :smile_cat:

**Comment by gtawebb** [comment]
Thanks, i tried but no success. I'll let you know if i find the solution. Let me know if you think of anything else. Is [oauth_signature_method] => HMAC-SHA256 as expected?
I might just go ahead with SSL and see if that method is successful.

**Comment by maxrice** [comment]
`HMAC-SHA256` as the signature method is expected. SSL should work without issue I think.

**Comment by gtawebb** [comment]
SSL worked fine. Thanks George

**Comment by mohammadfurqanofficial** [comment]
I want to insert custom field saved in item meta and when I'm placing order through website showing meta in order. but when I'm trying to post order through API then not getting in order...can anyone help me to resolve
