### ISSUE TITLE
customers->get_orders fails to recognise valid customer ID

### ISSUE THREAD

**Issue by gtawebb** [kloon/WooCommerce-REST-API-Client-Library#94]
print_r( $client->customers->get_orders( 5 ) ) 

produces the following error:

Error: Invalid customer ID [woocommerce_api_invalid_customer_id]

However the customer ID works fine with other woocommerce API calls. (eg //print_r( $client->customers->get( 5 ) );)

If I call: 	

print_r( $client->orders->get( 1633 ) );

It actually shows "customer_id":5 as part of the response.

Please could you check that the function is working correctly?  

I manually created the order, however it seems to be listed correctly and it is returned as an order.

Thanks.

**Comment by maxrice** [comment]
If you log into your WP admin and go to Users, does one exist for ID = 5?

**Comment by gtawebb** [comment]
There's no column for ID, however if I put 5 into the search box it returns the expected member (who is an admin), so yes is the answer.

I've tried with another (non admin) account, ID=169, and get the same issue. 

If i do:
print_r( $client->customers->get( 169) );

I get the following as part of my response.. 	
print_r( $client->customers->get( $customer_id ) );
     [body] => {"customer":{"id":169,"created_at":"2015-07-07T14:45:16Z","email":"support@XXX.com","first_name":"","last_name":"","username":"support","role":"subscriber","last_order_id":"1660","last_order_date":"2015-07-08T09:06:40Z","orders_count":1,"total_spent":"0.00","avatar_url":"https:\/\/1.gravatar.com\/avatar\/?s=96","billing_address":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":"","email":"","phone":""},"shipping_address":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":""}}}
                    

This shows that there is a user with ID=169 and that they had an order with ID=1660, which suggests that print_r( $client->customers->get_orders( 169 ) ); should not return "Error: Invalid customer ID [woocommerce_api_invalid_customer_id]"

The only unusual thing I'm doing is manually creating the order for the user but I shouldn't expect this to be an issues. I set the status to complete.

**Comment by maxrice** [comment]
Very strange, if you request an order for that user ID = 169, does it still return the invalid customer ID error?

**Comment by gtawebb** [comment]
Yes, as stated above. (I've tried with another (non admin) account, ID=169, and get the same issue.)

Also, 
print_r( $client->orders->get( 1674 ) ) 
returns 
[customer_id] => 5 
as part of the response but 
print_r( $client->customers->get_orders( 5 ) ); 
returns 
[woocommerce_api_invalid_customer_id]"

Could there be something wrong with the method $client->customers->get_orders( 5 )?

**Comment by gtawebb** [comment]
I think I have found the answer to this. It's because my users have subscriber roles as opposed to customer roles. I will look into this a bit further and report back.

**Comment by gtawebb** [comment]
Unfortunately, while this now allows me to get a response from:

/wc-api/v2/customers

{"customers":[{"id":172,"created_at":"2015-07-10T17:32:40Z","email":"support@xxx.com","first_name":"","last_name":"","username":"support","role":"customer","last_order_id":"1723","last_order_date":"2015-07-11T10:51:27Z","orders_count":4,"total_spent":"12.00","avatar_url":"https:\/\/2.gravatar.com\/avatar\/?s=96","billing_address":{"first_name":"G","last_name":"W","company":"","address_1":"1 impasse grande terre","address_2":"","city":"xx","state":"","postcode":"xx","country":"FR","email":"support@xxx.com","phone":"1234567"},"shipping_address":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":""}}]}

I still get the error from:

/wc-api/v2/customers/172/orders

{"errors":[{"code":"woocommerce_api_invalid_customer_id","message":"Invalid customer ID"}]}

I have no idea why so any suggestions would be much appreciated.

**Comment by gtawebb** [comment]
I've continued this issue at https://github.com/woothemes/woocommerce/issues/8561 so please add any suggestions there.  If I hardcode the ID within the class 'class-wc-api-customers.php' it then works properly. Thanks.
