### ISSUE TITLE
Invalid order is not developer friendly

### ISSUE THREAD

**Issue by jarodium** [kloon/WooCommerce-REST-API-Client-Library#97]
When I stumble into a invalid order id, let's say I supply a list of orders and one of them was misstyped.
The lib aborts a foreach loop I have in place and does not quietly return an array so that I can present my user which was the invalid order id.

**Comment by maxrice** [comment]
can you post the relevant snippet of your code here?

**Comment by jarodium** [comment]
Hello
Code below:

``` php
$pr = explode(",",$_POST["nencs"]);
foreach($pr as $pp) {
    $pro = $client->orders->get( $pp );
    if (!isset($pro["order"])) {
          //aborts with not found and a debug.
          $errors[] = '<div class="alert alert-danger" role="alert"><b>Order: $pp</b> not found!</div>';
    }
   else {
        //keep processing order
   }
}
```

I have rechecked the my code and found that I have debug = true, but still I feel it should not abort execution when does not find the order.

**Comment by maxrice** [comment]
the `$client` can throw `WC_API_Client_Exception` exceptions, so you'll need to account for that in your code.
