### ISSUE TITLE
when request all products it gives only few products

### ISSUE THREAD

**Issue by uresh** [kloon/WooCommerce-REST-API-Client-Library#98]
Hi when i send $client->products->get() . it will return with few products(10).
i compared with displayed products and others but no different couldn't find.

when  i send $client->products->get_count() it return number of products(130).

 i try to get product by id that product not list in product list ($client->products->get()) and it gives "No product found with the ID equal to 336"

**Comment by maxrice** [comment]
use `$client->products->get(null, array( 'limit' => 130 ) );` to get all 130 products.

**Comment by uresh** [comment]
cant we get all product without set limit. because no of product can be increase in future.

**Comment by uresh** [comment]
i tried with adding $client->products->get(null, array( 'limit' => 130 ) ); still gives 10 products. problem with wordpress, woocommerce or... product data ??? do you have any idea ??

**Comment by uresh** [comment]
$client->products->get(null, array( 'filter[limit]' =>130 ) );

**Comment by maxrice** [comment]
sorry, typo -- try `$client->products->get( null, array( 'filter[limit]' => 130 ) );`. If you want _all_ products, you can try `$client->products->get( null, array( 'filter[limit]' => -1 ) );`, but it's likely to timeout after some number of products. I'd recommend getting them in batches of 100 or so and paginating through them client-side :smile:

**Comment by uresh** [comment]
both not working i cant understand what might be the prob :(

**Comment by uresh** [comment]
finally working... :)
actually i use following method to pass values. 
$filters1=null;
$filters2=array( 'filter[limit]' => -1 );
$rest_method_par1="products";
$rest_method_par2="get";
$client->$rest_method_par1->$rest_method_par2($filters1,$filters2);

and replace " to '
$rest_method_par1='products';
$rest_method_par2='get';

when use " $filters2 value not passing . 
thanks for you support

**Comment by Ezhilarasu1330** [comment]
/wp-json/wc/v2/products/  When i use this API to get products. It fetches only 10 products

**Comment by Robert-Held** [comment]
@Ezhilarasu1330 
Sorry, but this will sound a bit harsh, I assume. This is the default behavior of this client, which has been document quite well until now (even in this thread). You must set a filter for a limit (as written in this thread) to change this retrieve more entries.

**Comment by Ezhilarasu1330** [comment]
I have tried to get products from woocommerce with POSTMAN API with my credentials. It fetches only 10 products. I need to fetch all the products
