### ISSUE TITLE
how to manage Variable products (sub sku)

### ISSUE THREAD

**Issue by uresh** [kloon/WooCommerce-REST-API-Client-Library#99]
how to manage Variable products. if product have sub sku.
eg: i have LED-30W product under that product have variation tab and its give me facility to add different type of bulb (base on color) and it's attributes(sku,qty,price and etc..)

i need to update these product stock and price using api ?

**Comment by maxrice** [comment]
Get the product IDs for the variations and you can update them using `$client->products->update( $id, array(...) )` :smile:

**Comment by uresh** [comment]
ok thanks :)
